### ISSUE TITLE
[Suggestion] Can you add Debian Testing repository to Bedrock Linux?

### ISSUE THREAD

**Issue by setsunati** [bedrocklinux/bedrocklinux-userland#101]
So i can do sudo brl fetch debian-testing

So i can get bleeding-edge packages from Debian repos on Linux Mint 19.1 Cinnamon which is based on Ubuntu and Debian LTS therefore has outdated packages by default. This will avoid me having to rely on PPA's for getting latest software's on Ubuntu/Mint. And since its all Debian/Ubuntu base, i think compatibility will be much better compared to say Arch which is very different than Debian/Ubuntu.

**Comment by paradigm** [comment]
Already supported via:

```
brl fetch debian -r testing
```

See `brl fetch --help` [or the website's documentation](https://bedrocklinux.org/0.7/commands.html#brl-fetch).

**Comment by setsunati** [comment]
Awesome. :)
