### ISSUE TITLE
Add snap support if it is installed.

### ISSUE THREAD

**Issue by xacrimon** [bedrocklinux/bedrocklinux-userland#102]
So, i just installed Bedrock. I noticed that no snap support exists. The missing parts are config changes relating to path and xdg data directories for the .desktop files.

paradigm helped solve these with me in IRC (big thanks).

Similiar support should also be considered for flatpak.

**Comment by xacrimon** [comment]
Directories to be added are `/snap/bin` for PATH and `/var/lib/snapd/desktop` for XDG_DATA_DIRS

**Comment by xacrimon** [comment]
Flatpak XDG_DATA_DIR is `/var/lib/flatpak/exports/share` and `~/.local/share/flatpak/exports/share`

**Comment by paradigm** [comment]
Thanks!  When I get the chance I'll test to confirm they work as I'm imagining, and if so push an update with these new envvar items in place.

**Comment by paradigm** [comment]
They are now included in the default `bedrock.conf` in 0.7.2.
