### ISSUE TITLE
[Suggestion] Add documentation for being able to choose what stratum is used when command is avaliable in multiple.

### ISSUE THREAD

**Issue by fosslinux** [bedrocklinux/bedrocklinux-userland#105]
Going through the Bedrock docs, it came to my attention that there does not seem to be a way to **manually** select which stratum is used when the command is available in multiple stratum.

> If you have multiple strata provide the same command, absent any additional indication of which to use Bedrock will choose one by default in a given context.

Apparently this is possible, but there is no documentation on the website for it.

**Comment by Mouvedia** [comment]
check https://github.com/bedrocklinux/bedrocklinux-userland/issues/99#issuecomment-451668203

**Comment by paradigm** [comment]
Bedrock Linux does have such a feature.  It's described in the comments in `/bedrock/etc/bedrock.conf` but apparently *not* [in the website's configuration documentation](https://bedrocklinux.org/0.7/configuration.html).  The website should document it as well.  I'll update it accordingly when I get time.

Bedrock puts `/bedrock/cross/pin/` at the front of your `$PATH` for this purpose, which is noted in the comments [here](https://github.com/bedrocklinux/bedrocklinux-userland/blob/8e059d5aa98981261e81abab1845218953f3b39d/src/slash-bedrock/etc/bedrock.conf#L240-L243).  Read the comments [here](https://github.com/bedrocklinux/bedrocklinux-userland/blob/8e059d5aa98981261e81abab1845218953f3b39d/src/slash-bedrock/etc/bedrock.conf#L287-L327) to learn how to configure Bedrock's cross subsystem to populate that directory with a new entry.  You can use `reboot` as a reference, [as shown here](https://github.com/bedrocklinux/bedrocklinux-userland/blob/8e059d5aa98981261e81abab1845218953f3b39d/src/slash-bedrock/etc/bedrock.conf#L362).  You'll probably want to add your new item(s) [here](https://github.com/bedrocklinux/bedrocklinux-userland/blob/8e059d5aa98981261e81abab1845218953f3b39d/src/slash-bedrock/etc/bedrock.conf#L365).  After you've made the configuration changes, run [`brl apply` as root](https://bedrocklinux.org/0.7/commands.html#brl-apply) to apply them.  Once that's done, [`brl which`](https://bedrocklinux.org/0.7/commands.html#brl-which) should reflect the configuration and the new pinned stratum should be applied when running the command.

Apologies for not having this up on the website.  I'm currently swamped with support requests and it might take me a bit to get to this, but I will at some point.  Feel free to leave this issue open as an indication that I need to update the website until I've done so.

**Comment by fosslinux** [comment]
Thanks!

**Comment by paradigm** [comment]
Documented [here](https://bedrocklinux.org/0.7/workflows.html#pinning).
