### ISSUE TITLE
Suggestion: Bedrock Linux Distro

### ISSUE THREAD

**Issue by setsunati** [bedrocklinux/bedrocklinux-userland#117]
Why is there no Linux Distro ISO of Bedrock Linux? 

If you decided to make a full Bedrock Linux Distro sometime in future in order for seamless Bedrock Linux Package Manager integration for out of the box functionality:

You can base Bedrock Linux Distro on Intel Clear Linux rolling OS https://clearlinux.org/ which doesn't have packages in traditional sense like most Linux distros. Instead of traditional packages, Clear Linux uses containerized bundles. https://clearlinux.org/documentation/clear-linux/concepts/swupd-about#bundles

By combining Bedrock Linux with Intel Clear Linux OS. I think we will have a great Linux distro, different from any other Linux distro. :)

**Comment by paradigm** [comment]
We *might* be on different pages about Bedrock Linux's goal.  I'll summarize the relevant part here to rule out that possibility:

Bedrock Linux is meta Linux distribution built out of features of other Linux distributions (which may be, under normal circumstances without things like Bedrock, mutually exclusive).  You can get your kernel from one distro, your Xorg from another, your text editor from yet a third, etc.  We consider the installation process as such a feature.  Some users prefer certain installation processes and some prefer others; Bedrock's goal with installers - just like its goal with every other feature - is to let you choose.  If you prefer a user friendly installer where you fill out some fields in a GUI then click next a few times, you can install Bedrock using the installer provided Ubuntu, Mint, etc.  If you prefer a more hands on install process, you can install Bedrock using Arch's or Gentoo's or even LFS's install process.  If you prefer Clear Linux's installer for whatever reason, you're welcome to use that as well.

Given this, it sounds like you're proposing dropping Bedrock's ability to let users get their install process from other distros and mandating everyone use Clear Linux's installer.

I don't see any advantage to doing so.  I just see the loss of a defining feature.  If you think I am misunderstanding you, can you elaborate more to clear things up?  If I grasped your proposal correctly but am failing to see its advantages, can you list those out for me more explicitly?

**Comment by setsunati** [comment]
No, i am not proposing dropping Bedrock's ability to let users get their install process from other distros. You can continue offering Bedrock Linux meta Linux distro as usual that users can install on their preferred distro. 

What i am suggesting is offering a Clear Linux based full Bedrock Linux distro ISO in addition, where Bedrock Linux is included in this Clear Linux distro out of the box. Similar to how KDE devs have combined Ubuntu distro and KDE Plasma and offer KDE neon ISO for example.

You or someone else interested in creating Clear Linux based Bedrock Linux distro can do it.

**Comment by paradigm** [comment]
In that case, I still see cost in terms of work to setup and maintain, and I am still unable to see any advantage.  With Bedrock, you can _already_ use Clear Linux's install process.

Can you elaborate on the advantage that has over what Bedrock already offers?

**Comment by setsunati** [comment]
Advantage i think would be out of the box/pre-configured Bedrock on Clear Linux. A Linux Mint of Bedrock Linux and Clear Linux pretty much, where it is setup like it just works. So newbie friendly.

**Comment by paradigm** [comment]
If I'm following correctly, the value here is save those who want to use Bedrock Linux on x86_64 with Clear Linux's installer from downloading and running a single script.

This seems to be a *very* limited time saver for a *very* limited audience.  I don't think it's worth the effort for us to maintain an ISO, keeping it up to date with both Clear Linux and Bedrock Linux changes, as well as distribute the ISO.  In fact, to do Clear Linux justice, it would likely be multiple ISOs - they have different images for different out-of-the-box feature sets and environments.

I'm also concerned its going to exacerbate confusion over what Bedrock Linux actually is, as well as lead to endless requests to create ISOs that come with the script baked in with the installers for other distros.

If you personally install Bedrock Linux *so often* that the cost to download a ~1MB script and run it is problematic, you're certainly welcome to bake it into the installer of your choice to save you time.  It is GPLv2, go nuts.  However, for a broader audience, the cost/benefit does not seem anywhere near worthwhile.

**Comment by SolitudeSF** [comment]
installing bedrock is 2 commands, wget and hijack. it literally nothing compared to maintenance cost implied by this feature request. also choosing `clear linux` as *main* distribution is absolutely wrong. you are free to maintain your own images with bedrock preinstalled, but i feel like its out of the scope of this project.

**Comment by paradigm** [comment]
It seems like the consensus is against this proposal and there is no further action to change the consensus, and so I am closing it.  If you think up what you believe is a good counter argument to the provided criticisms, do feel free to re-open the issue.
