### ISSUE TITLE
LVM support

### ISSUE THREAD

**Issue by nift4** [bedrocklinux/bedrocklinux-userland#129]
I know this is listed on the website. Here I want to discuss solutions.

Is http://www.tldp.org/HOWTO/LVM-HOWTO/lvm2_boot.html enough to make lvm work?

**Comment by nift4** [comment]
I need to know where I can add that lines in Bedrock :) Then I'll try out for myself (and if it works i'll send a pull)

**Comment by paradigm** [comment]
Relevant background on why this is an open issue:

- Central to how Bedrock Linux works is manipulating the virtual filesystem layer via mount points.  Bedrock sets such mount points up before handing control off to the selected init.
- When the selected init goes to mount `/etc/fstab`, it skips any lines corresponding to directories that already have _something_ mounted on them, assuming the desired mount is already set up.  This means it skips mounting over Bedrock's mount points, which in turn means it may skip things like dedicated `/home` partitions.
- To fix this, Bedrock mounts `/etc/fstab` itself before handing control off to the selected init.  This is how non-LVM dedicated `/home` partitions work in Bedrock.
- Bedrock proper lacks LVM tools required to mount `/etc/fstab` entries corresponding to LVM mounts.
- Bedrock cannot get such things from other strata, as setting up all the mounts is a prerequisite to enabling those strata; it's a catch-22.

The fix I have in mind here is to build LVM tools like `dmsetup` and/or whatever else is necessary and include them in Bedrock proper so Bedrock can use them to set things up itself, then add whatever changes are necessary to Bedrock's `/etc/fstab` mount code to utilize them.

For example an example of adding a third party utility to Bedrock's core, see how it handles `busybox` or `netselect`.  One will need to:

- [Add a recipe to fetch the upstream source](https://github.com/bedrocklinux/bedrocklinux-userland/blob/683e0f38531d4e0971aaeb29873f1bf98b534c0d/Makefile#L373-L382)
- [Add a recipe to build the utility against musl-libc](https://github.com/bedrocklinux/bedrocklinux-userland/blob/683e0f38531d4e0971aaeb29873f1bf98b534c0d/Makefile#L383-L462)
- [Register the fetch code with a recipe for grabbing all sources](https://github.com/bedrocklinux/bedrocklinux-userland/blob/683e0f38531d4e0971aaeb29873f1bf98b534c0d/Makefile#L205)
- [Register the utility code with a recipe for building the userland](https://github.com/bedrocklinux/bedrocklinux-userland/blob/683e0f38531d4e0971aaeb29873f1bf98b534c0d/Makefile#L573)

Bedrock's code to mount `/etc/fstab` is [here](https://github.com/bedrocklinux/bedrocklinux-userland/blob/683e0f38531d4e0971aaeb29873f1bf98b534c0d/src/init/init#L361).  If anything needs to be added to mount LVM items, that's probably the place to do it.  We should make sure it handles both LVM scenarios and the scenario where there's no LVM in play at all.

Once those changes are in place, a `make SKIPSIGN=true` should build an installer/updater which includes the utility and any changes to the `init` file.  Maybe test with `make remove_vendor_source && make clean` to make sure it can build from a fresh slate.  The resulting installer/updater could then be used to test hijacking an LVM setup on a spare machine / VM / whatever.

While it's not overly important to get it perfectly, if anyone wants to pursue this, try to minimize the size/count of the utility/utilities being added.  If you can remove something unneeded at build time, please do so.  People use Bedrock not for itself, but to utilize software from other distros; Bedrock proper is, in some sense, pure overhead which we should try to keep as small as is feasible.

**Comment by nift4** [comment]
Thx for the explainaiton. I'll try with debian bins first.

**Comment by paradigm** [comment]
Debian's binaries are dynamically linked against Debian's libraries:

```
$ strat debian ldd /sbin/dmsetup
        linux-vdso.so.1 (0x00007ffe80fc5000)
        libdevmapper.so.1.02.1 => /lib/x86_64-linux-gnu/libdevmapper.so.1.02.1 (0x00007fe368233000)
        librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007fe36802b000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fe367c8c000)
        libselinux.so.1 => /lib/x86_64-linux-gnu/libselinux.so.1 (0x00007fe367a64000)
        libudev.so.1 => /lib/x86_64-linux-gnu/libudev.so.1 (0x00007fe368891000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fe367847000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fe367543000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fe3686ac000)
        libpcre.so.3 => /lib/x86_64-linux-gnu/libpcre.so.3 (0x00007fe3672d0000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fe3670cc000)
```

Running it directly from the `bedrock` stratum without something like `strat` won't work.  You'll get a not found error, where it's confusingly referring to the library rather than the executable being run:

```
$ strat bedrock ls /bedrock/strata/debian/sbin/dmsetup
/bedrock/strata/debian/sbin/dmsetup
$ strat bedrock /bedrock/strata/debian/sbin/dmsetup 
strat: could not run
    /bedrock/strata/debian/sbin/dmsetup
from stratum
    bedrock
due to: unable to find file (ENOENT)
$ strat bedrock sh -c 'ls /bedrock/strata/debian/sbin/dmsetup'
/bedrock/strata/debian/sbin/dmsetup
$ strat bedrock sh -c '/bedrock/strata/debian/sbin/dmsetup' 
sh: /bedrock/strata/debian/sbin/dmsetup: not found
```

Resolving stuff like that is why Bedrock is needed in the first place.

`strat debian` won't work either, because the stratum hasn't been enabled, because of the aforementioned catch-22:

```
$ strat debian /sbin/dmsetup
strat: could not find state file for stratum
    debian
at
    /bedrock/run/enabled_strata/debian
Perhaps the stratum is disabled or typo'd?
```

You could probably get something working by:

- Mounting any dependencies like `procfs`, `/dev`, etc into `/bedrock/strata/debian`
- `chroot`'ing into `/bedrock/strata/debian` and running the LVM commands
- Using `mount --move` to move the new mounts out of `/bedrock/strata/debian` and onto the root of the filesystem.

although I'm not sure what good that does you.

This is why the proper fix involves making a copy of the relevant executables that can run directly in the `bedrock` stratum.

**Comment by nift4** [comment]
Chroot'ing can't work because someone can have /bedrock/strata/debian on a LVM partiton.

**Comment by nift4** [comment]
Trying to create statically linked bins...

**Comment by nift4** [comment]
Statically can't work, so created dynamically linked bins and copied libs, now trying out in the VM...

**Comment by nift4** [comment]
One question: when bedrock boots, is bedrock strata available or where I should place the bins to run from init? @paradigm

**Comment by nift4** [comment]
Okay seems with musl I can link statically, but have to test.

**Comment by paradigm** [comment]
> Chroot'ing can't work because someone can have /bedrock/strata/debian on a LVM partiton.

Right, my intent there was a quick and dirty test, as that's what I had thought you intended with Debian's binaries.  I would strictly not accept such a thing for up streaming as a long term solution.

> Statically can't work, so created dynamically linked bins and copied libs, now trying out in the VM...

I strongly prefer statically linking within Bedrock's build system here.  If your goal is a quick and dirty test, we can continue with dynamically linked binaries and libraries with the intent of wrapping back around and making statically linked ones.  However, given the fact you recognized chroot'ing wouldn't be viable as a long term solution, maybe you're working directly on an upstreamable solution, in which case we should discuss why static linking can't work now before continuing.

> One question: when bedrock boots, is bedrock strata available or where I should place the bins to run from init? @paradigm

At the part of the boot process we're discussing, the local stratum is the `bedrock` stratum.

If you can get static binaries (which is strongly preferred) they should probably be placed in `/bedrock/libexec`.  You can either just directly copy them there for a quick test, or if you want to integrate them into the installer/updater, reference `busybox` in Bedrock's Makefile [here](https://github.com/bedrocklinux/bedrocklinux-userland/blob/683e0f38531d4e0971aaeb29873f1bf98b534c0d/Makefile#L461) and [here](https://github.com/bedrocklinux/bedrocklinux-userland/blob/683e0f38531d4e0971aaeb29873f1bf98b534c0d/Makefile#L573).

If you are continuing with dynamically linked binaries, they should be placed in the `bedrock` stratum's local files.  You can either copy them into `/bedrock/strata/bedrock/`, or if you want to integrate them into the installer/updater, reference [`init` in Bedrock's Makefile](https://github.com/bedrocklinux/bedrocklinux-userland/blob/683e0f38531d4e0971aaeb29873f1bf98b534c0d/Makefile#L190-L192).

**Comment by nift4** [comment]
@paradigm Because I want to create a upstreamable solution here is the reason why lvm2 can't work statically (it can theoretically build): udev needs to be dynamically linked. There is a fork that is able to get statically linked, libeudev, but that doesn't generates working binaries.

And here a very big thanks to being so competent and helpful.

**Comment by nift4** [comment]
What about using lvm libs from a strata and coping them while hijacking?

**Comment by nift4** [comment]
That would also ensure that LVM versions in kernel and tools match.

**Comment by paradigm** [comment]
> @paradigm Because I want to create a upstreamable solution here is the reason why lvm2 can't work statically (it can theoretically build): udev needs to be dynamically linked. There is a fork that is able to get statically linked, libeudev, but that doesn't generates working binaries. Some docker guys tried it, they wanted standalone dockerd with lvm.

Do we need udev bits for what we're doing here?  [Some quick/shallow searching makes it seem like it might not be necessary](https://unix.stackexchange.com/questions/81507/gentoo-how-to-compile-lvm-statically-linked).  In theory we just need enough to statically setup the system before handing off the init, which would then do udev stuff to handle dynamic changes.  Admittedly, I don't know LVM well at all and could be missing something significant here.

> And here a very big thanks to being so competent and helpful.

Happy to help :)

Bedrock is a big project and requires a fair bit of cooperation, patience, and teamwork to continue to grow.

> What about using lvm libs from a strata and coping them while hijacking?

I still strongly prefer to fully explore the possibility of creating our own static binaries first, but if we exhaust that completely, this is an option we could consider.

I _think_ I'd prefer we make our own dynamically linked version than trying to nab those from the hijacked distro.  Without thinking about it to deeply, just off the cuff:

- Trying to figure out exactly what files to grab could be finicky.
- Different distros will place executables and libraries in different places.  To make sure things link up, we'll have to files in the `bedrock` stratum in the places corresponding to the hijacked distro, which in turn will result in inconsistent `bedrock` layouts.
- The Linux ecosystem is usually good about being backward compatible.  Using our own would let us target a relatively recent version of LVM which should work on older distros.  However, the other way may not work; if we hijack an older distro and use older LVM stuff, then the user makes a new LVM partition using stuff from another newer distro, it may no longer work.

That having been said, I could easily change my mind here after thinking about it more.

> That would also ensure that LVM versions in distro and while booting match.

This is only the case if users continue to use the hijacked distro for their init, which is something Bedrock very explicitly does not require.  The whole point of Bedrock is to let people mix and match stuff, and so they should be free to get their install process from one distro, then init from another, should they choose to do so, provided we can make that work.

**Comment by nift4** [comment]
Okay, that info I missed. UDev is a part from systemd, we do not run systemd at this stage and it should work without udev. I'll try to build statically again.

**Comment by nift4** [comment]
`checking for libaio.h... no
configure: error: bailing out
make: *** [Makefile:530: vendor/lvm2/.build] Fehler 1
`
while configure

**Comment by nift4** [comment]
Should we build `libaio`? It's installed on my system but musl can't use it in the path.

**Comment by nift4** [comment]
As quick-and-dirty fix I'll copy the header file :)

**Comment by nift4** [comment]
Then there is missing the `-lblkid`

**Comment by nift4** [comment]
I can't fix that with copy-paste.

**Comment by nift4** [comment]
blkid is from util-linux-ng

**Comment by nift4** [comment]
If you're intrested in my [Makefile](https://github.com/bedrocklinuxcommunity/bedrocklinux-userland/blob/master/Makefile) here are some notes:
* `-I./icl` is the q&d fix for libaio.h
* It only builds it and puts it into the binary, nobody does something with it
* LVM is distributed though TGZ files and because of that I haven't implemented a download.

**Comment by nift4** [comment]
ftp://sources.redhat.com/pub/lvm2/

**Comment by nift4** [comment]
#130 @paradigm Can you please decide? Then I can continue working.

**Comment by paradigm** [comment]
@nift4 I do not follow what you want me to decide about.  I might have lost context.  Could you elaborate?

**Comment by nift4** [comment]
Should we build dependencies or not? And if not, there from where?

**Comment by paradigm** [comment]
[From the Makefile](https://github.com/bedrocklinux/bedrocklinux-userland/blob/683e0f38531d4e0971aaeb29873f1bf98b534c0d/Makefile#L37-L41):

> This build system attempts to strike a balance between being overly dependent
> on the host system at the expense of portability, and maximizing portability
> at the expense of build time.  Build tools such as gcc and meson are taken
> from the host system rather than recompiled.  Upstream code which ends up
> within the output script is compiled from source.

See `libfuse` for an example of a library dependency that Bedrock's build system fetches and builds.  Please read through the existing `Makefile` for similar questions, as it explains itself with comments and plenty of examples.

**Comment by nift4** [comment]
The other deps are `libaio`, `libpcre`, `libuuid`, `libpthread`, `libdl`, `libselinux` and `libblkid`. I think we can remove selinux but for the others IDK.

**Comment by paradigm** [comment]
Lets give it a try and lets see how bug the resulting binaries are.  It's going to be disappointing if we have to double Bedrock's disk footprint for this specific feature, but c'est la vie.

**Comment by nift4** [comment]
What's c'est la vie? I know it's french but I do not speak it :) Anyway I looked at `./configure --help

**Comment by nift4** [comment]
Oops

**Comment by paradigm** [comment]
I think the best translation would be "that's life."  It carries a similar sentiment to "oh well."

**Comment by nift4** [comment]
Okay. Look at the updated lib list :)

**Comment by paradigm** [comment]
Nice job cutting the count in half :)  Hopefully those dependencies don't have too many dependencies of their own.

**Comment by nift4** [comment]
What's the difference between vendor/ and $(VENDOR)?

**Comment by nift4** [comment]
@paradigm yay, got dmsetup working, lvm does not find the own libary.

**Comment by nift4** [comment]
`=== Completed creating bedrock-linux-0.7.6-x86_64.sh ===`

**Comment by nift4** [comment]
Now testing ... :)

**Comment by nift4** [comment]
Okay @paradigm I got it alsmost working...

**Comment by nift4** [comment]
But one issue is left, I troubleshoot and post it here.

**Comment by nift4** [comment]
When it boots, my /dev/test/test gets mounted to /bedrock/strata/bedrock/mnt/test (in fstab /mnt/test), that confuses systemd. How to fix that?

**Comment by nift4** [comment]
@paradigm ??

**Comment by paradigm** [comment]
> What's the difference between vendor/ and $(VENDOR)?

[When I build a release copy of Bedrock, I run multiple builds for different architectures in parallel](https://github.com/bedrocklinux/bedrocklinux-userland/blob/683e0f38531d4e0971aaeb29873f1bf98b534c0d/Makefile#L664-L708).  Each has their own, incompatible build artifacts, and so [I make a per-architecture build directory `$(BUILD)`](https://github.com/bedrocklinux/bedrocklinux-userland/blob/683e0f38531d4e0971aaeb29873f1bf98b534c0d/Makefile#L131) to keep them from stepping on each other when running in parallel.  [`$(SRC)` and `$(VENDOR)` are places in `$(BUILD)` for the corresponding items to place their build artifacts.](https://github.com/bedrocklinux/bedrocklinux-userland/blob/683e0f38531d4e0971aaeb29873f1bf98b534c0d/Makefile#L132)

For example, [`linux_headers` is configured to place its build artifacts in `$(VENDOR)/linux_headers`](https://github.com/bedrocklinux/bedrocklinux-userland/blob/683e0f38531d4e0971aaeb29873f1bf98b534c0d/Makefile#L132).  In some places [I just copied source code into `$(BUILD)` and had it dump artifacts in the (new) source code location](https://github.com/bedrocklinux/bedrocklinux-userland/blob/683e0f38531d4e0971aaeb29873f1bf98b534c0d/Makefile#L132) as a quick hack.  I'd prefer the former, but for your PR you're welcome to do either.  Eventually I hope to go rework things to only one architecture-independent copy of the source code and per-architecture copies of the build artifacts.

This is not well documented in the `Makefile` and a completely reasonable question.  I should probably refactor this and/or add comments to be more clear.  I'll need to think it through, but my gut reaction is to add a comment by where `$(BUILD)` is defined explaining the architecture differentiation, then to remove `$(VENDOR)` and `$(SRC)` and just dump the sub-project artifacts in `$(BUILD)/$(PROJECT)`, e.g. `$(BUILD)/netselect` rather than `$(BUILD)/vendor/netselect`.  Combine with the aforementioned goal of dropping the source copy and _just_ configuring build artifacts to go there, I think it should be much more clear.

> `=== Completed creating bedrock-linux-0.7.6-x86_64.sh ===`

What's the resulting file size?  We'll probably roll with it, whatever it is, but I can't help but be curious how much disk usage this is adding.

> When it boots, my /dev/test/test gets mounted to /bedrock/strata/bedrock/mnt/test (in fstab /mnt/test), that confuses systemd (I think). Systemd has a waiting for /mnt/test job that expires after time and the recovery shell boots. How to fix that?

I don't know off the top of my head.  I'm not as knowledgable with either LVM or systemd as I'd like to be.  We'll have to debug it and do research.  You're certainly welcome to dig into it and see if you can figure it out.  If you don't I will be happy to, but it may take me quite a while to dig through higher priority items so I can find the time.

**Comment by nift4** [comment]
> What's the resulting file size? We'll probably roll with it, whatever it is, but I can't help but be curious how much disk usage this is adding.
2,2 MB

**Comment by nift4** [comment]
> When I build a release copy of Bedrock, I run multiple builds for different architectures in parallel. Each has their own, incompatible build artifacts, and so I make a per-architecture build directory $(BUILD) to keep them from stepping on each other when running in parallel. $(SRC) and $(VENDOR) are places in $(BUILD) for the corresponding items to place their build artifacts.

For example, linux_headers is configured to place its build artifacts in $(VENDOR)/linux_headers. In some places I just copied source code into $(BUILD) and had it dump artifacts in the (new) source code location as a quick hack. I'd prefer the former, but for your PR you're welcome to do either. Eventually I hope to go rework things to only one architecture-independent copy of the source code and per-architecture copies of the build artifacts.

This is not well documented in the Makefile and a completely reasonable question. I should probably refactor this and/or add comments to be more clear. I'll need to think it through, but my gut reaction is to add a comment by where $(BUILD) is defined explaining the architecture differentiation, then to remove $(VENDOR) and $(SRC) and just dump the sub-project artifacts in $(BUILD)/$(PROJECT), e.g. $(BUILD)/netselect rather than $(BUILD)/vendor/netselect. Combine with the aforementioned goal of dropping the source copy and just configuring build artifacts to go there, I think it should be much more clear.

I copied the source :)

**Comment by nift4** [comment]
> I don't know off the top of my head. I'm not as knowledgable with either LVM or systemd as I'd like to be. We'll have to debug it and do research. You're certainly welcome to dig into it and see if you can figure it out. If you don't I will be happy to, but it may take me quite a while to dig through higher priority items so I can find the time.

First problem I discovered:
`DEVNAME: /dev/dm-0
SYSTEMD_READY=0`

**Comment by nift4** [comment]
Exactly in the intresting point the logs are too fast for syslog :cry:

**Comment by nift4** [comment]
and log level info segfaults :angry:

**Comment by nift4** [comment]
How I should debug, systemd???

**Comment by nift4** [comment]
Now info does not segfault...

**Comment by nift4** [comment]
@paradigm Got it!!!!!!

**Comment by nift4** [comment]
If you add the line `ExecStart=/bin/udevadm trigger --type=devices --action=change` to `bedrock-fix-mounts.service`, after the other ExecStart, it simply works.

The problem is that we compiled LVM2 without udev support, so LVM can't tell udev that it's ready. The line does that.

**Comment by nift4** [comment]
Testing, with following env:

    sda1 ext4 /
    sda2 luks sda2_crypt
    sda2_crypt lvmpv vg
    vg lvmvg
    home lvmlv vg ext4

**Comment by paradigm** [comment]
> It can fit on a 3,5 ED floppy, before an 3,5 HD :stuck_out_tongue_winking_eye:

Hah!  I was thinking about it in the same exactly framework.  I've been tempted to distribute the Bedrock installer on floppies at Linux conventions as a joke.

> If you add the line `ExecStart=/bin/udevadm trigger --type=devices --action=change` to `bedrock-fix-mounts.service`, after the other ExecStart, it simply works.
> 
> The problem is that we compiled LVM2 without udev support, so LVM can't tell udev that it's ready. The line does that.

Very nice job debugging the issue!  This makes perfect sense.

If you have time and interest - I don't want to demand too much here - do you mind building LVM2 with udev support as a test so we can compare the trade-offs?

I'm curious:

- How much does udev support add to disk size usage over what you have now.
- If LVM2 with udev support makes this work without that `ExecStart` change.
- How udev support but not `ExecStart` change changes boot time over what you have now.
	- Users have complained in the past about `bedrock-fix-mounts.service` taking too much time over existing boot time.

If that's a pain or you don't have the time, don't feel obligated to do so.

Also, if you have time and interest, it'd be good to test your changes against a number of distros and set ups.  Maybe a couple systemd distros and a couple non-systemd distros, as well as a mix of setups that use LVM and those that don't.  I plan to do this testing myself as well either way, but it'd be good for us to check each other's work.

Other than comparing against building with udev support and testing against various installs, is there anything else we need to do or is this looking good?

Assuming there's nothing else, when I find the time I'll be happy to review the MR you made and we can see about getting it merged.  There's a number of other Bedrock things I need to get done first, as well as non-Bedrock priorities in the near future I need to take care of, so it may take a number of weeks, but I'm very eager to see this merged and the LVM known issue dropped! :)

**Comment by nift4** [comment]
> do you mind building LVM2 with udev support as a test so we can compare the trade-offs?

I found out it can't work because we use LVM before systemd (and so systemd-udevd) is here. And I'm sure you don't want to integrate Systemd into Bedrock Linux.

> How much does udev support add to disk size usage over what you have now.

Read above :) and remember that udev must be dynamically linked so 0 except systemd.

> How udev support but not ExecStart change changes boot time over what you have now. 

Almost nothing, the command does the same and does not slow down anything.

>Users have complained in the past about bedrock-fix-mounts.service taking too much time over existing boot time.

It's probably the fastes service on my whole VM debian (and it's only a debian no X no desktop) :rofl:

> Also, if you have time and interest, it'd be good to test your changes against a number of distros and set ups. Maybe a couple systemd distros and a couple non-systemd distros, as well as a mix of setups that use LVM and those that don't. I plan to do this testing myself as well either way, but it'd be good for us to check each other's work.

I can try it but I can't promise anything.

> Assuming there's nothing else, when I find the time I'll be happy to review the MR you made and we can see about getting it merged. There's a number of other Bedrock things I need to get done first, as well as non-Bedrock priorities in the near future I need to take care of, so it may take a number of weeks, but I'm very eager to see this merged and the LVM known issue dropped! :)

Same! Missing LVM is the only reason that that my main Ubuntu is not a Bedrock Linux.

**Comment by nift4** [comment]
Added a web PR, link in the PR.

**Comment by nift4** [comment]
If I completed testing with debian I'll mark it ready for review but test with other distros.

**Comment by paradigm** [comment]
> I found out it can't work because we use LVM before systemd (and so systemd-udevd) is here. And I'm sure you don't want to integrate Systemd into Bedrock Linux.

You are surely correct.

> Read above :) and remember that udev must be dynamically linked so 0 except systemd.

Ahh that's right, I forgot that udev would require dynamic linkage.  That does rule that route out.  No worries, what you have here looks great for our needs.

> It's probably the fastes service on my whole VM debian (and it's only a debian no X no desktop) :rofl:

Excellent :)

> If I completed testing with debian I'll mark it ready for review but test with other distros.

Sounds good!  No promises about when I get around to reviewing it - maybe some weeks - but I'll do so as soon as the opportunity presents itself.  I'm very eager to get this in.

**Comment by nift4** [comment]
@paradigm
> Sounds good! No promises about when I get around to reviewing it - maybe some weeks - but I'll do so as soon as the opportunity presents itself. I'm very eager to get this in.

It's not even a big change, more figuring it out what to change :)

So have fun with reviewing.

**Comment by nift4** [comment]
And have noticed my web pr?

**Comment by paradigm** [comment]
> And I hope you noticed my web pr.

Yup, I saw it.  I'll get to it when I get the chance.

**Comment by nift4** [comment]
@paradigm works perfectly in debian :)

**Comment by nift4** [comment]
@paradigm Done more tests with Void, see Pull Request

**Comment by nift4** [comment]
@paradigm late info: I ensured `-f -` in tar commands for bsdtar.

**Comment by runningnak3d** [comment]
@nift4 @paradigm Just got testing on a Gentoo install that has two drives. It originally only had one drive, that was split into / and /home using LVM. Later when I added the second drive, I extended the VG that contained /home, so /home is half the first drive and all of the second. (I figure as many details as possible is always a good thing). 

Anyway, it worked flawlessly except for a passwd file issue that IMHO can't have anything to do with this patch. For some reason, when I booted, init either couldn't read or find the passed file because all the services were complaining about user root not existing. So I booted from a USB stick and copied the passwd, shadow and group files back into the now hijacked Gentoo strata's /etc and then it booted fine. Once booted, I was able to delete the passed, shadow and group files from the strata, and everything is working as it should. 

Again, I only provided the information about the passed file *just in case* I missed something with this patch, and somehow it caused that issue. I am baffled as to what would cause it.

Awesome job @nift4. This was my last machine that wasn't Bedrockified. I am going to stand up a Gentoo VM and test again .. but as I said, after reviewing your changes, I am 99.999% sure that there is no way that it could have caused that. I think it was an issue that I have had that Gentoo install for almost a decade and there was probably something I had done along the way that was hacked in for some purpose and I forgot about it.

**Comment by nift4** [comment]
@runningnak3d Cool :) Thanks for testing. The passwd issue is probably not the fault of my patch, eventually of etcfs (or really only your hack)? Anyway, it's really cool to know that it works. What init system is on the install? OpenRC (gentoo default as far i know)? Or systemd?

**Comment by runningnak3d** [comment]
@nift4 That Gentoo install is using OpenRC.
I am in the process of testing:
Ubuntu
Arch
Fedora
Alpine

I would test OpenSUSE and Exherbo, but I don't know those inside and out, and when doing tests like this -- IMHO -- you really need to know the distro backwards, forwards, up down, left right ;)

I am not going to do this for all the ones that I am testing, but I am going to pick one and go all out and put every mount on LVM. So:
/etc
/usr
/var
/home
etc...etc.. If the distro has a /something in its baselayout, and the distro itself allows that mount to be configured with LVM, then I am going to set it up that way. That is WAY over complicating things -- no one in their right mind would ever do that, but it tests an edge case. I am curious about /etc being on LVM though.

I will post the results as I get them.

**Comment by nift4** [comment]
Big thanks for testing all distros :) My HDD & internet is too slow for thousand big distros installing...

**Comment by nift4** [comment]
@paradigm Will LVM support be in 0.7.7?

**Comment by paradigm** [comment]
Absent some surprise issue which needs to be expedited, your LVM PR is scheduled for 0.7.8, along with Philantrop's Exherbo PR.  Your work here is greatly appreciated, and this is an often requested feature such that I know for a fact a number of people will be excited to see it land.  I definitely didn't forget about it.  However, my work queue here is pretty long and it's taking a while to filter through everything that needs to get done.
