### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by nift4** [bedrocklinux/bedrocklinux-userland#134]
Can we translate Bedrock Linux? (Installer,init and brl?) Is there any interest in a translation or would make this the scripts too complex? @paradigm

**Comment by paradigm** [comment]
In theory I would love for Bedrock to properly support multiple languages.  There would be associated complexity, but not so much to rule it out.  My primary concern here is that this will add regular overhead for each release to get all the translations in order.  Moreover, if we pursue this, we should probably also add translations for the website, which will further add overhead.  With Bedrock's current pre-1.0-stable phase of development I'd rather focus on getting the long list of needed technical improvements out of the way first with minimal additional overhead slowing us down.  Once we get near 1.0-stable where the under-the-hood churn slows down I'd very much like to pursue some sort of i18n support.
