### ISSUE TITLE
Add URL to GitHub metadata

### ISSUE THREAD

**Issue by nift4** [bedrocklinux/bedrocklinux-userland#135]
See title :) @paradigm

**Comment by paradigm** [comment]
I don't know what you mean.  Can you expand on the issue?

**Comment by nift4** [comment]
Okay. I'll post a screenshot.

**Comment by nift4** [comment]
https://www.directupload.net/file/d/5549/pml3fqp7_jpg.htm in my bedrocklinuxcommunity repo. Click "Edit".

**Comment by paradigm** [comment]
Ahh, I see.  I didn't know about that Github feature.  Done!
