### ISSUE TITLE
How to select a stratum to boot in without waiting 30 seconds or choosing ?

### ISSUE THREAD

**Issue by octavian124** [bedrocklinux/bedrocklinux-userland#136]

**Comment by nift4** [comment]
Kernel parameter `bedrock_init`. See https://bedrocklinux.org/0.7/debugging.html#bedrock-init . You can also chnage the Timeout and the default: https://bedrocklinux.org/0.7/configuration.html#init

**Comment by nift4** [comment]
@paradigm do you want to close this issue?

**Comment by nift4** [comment]
@octavian124

**Comment by octavian124** [comment]
Thx.
