### ISSUE TITLE
Add wget and rsync to the list of required software for building.

### ISSUE THREAD

**Issue by Sickday** [bedrocklinux/bedrocklinux-userland#154]
Not all distros ship with wget and/or rsync and this would help avoiding the below error when building the shell script.
![brl_req](https://user-images.githubusercontent.com/30793532/71642793-27e4db80-2c7f-11ea-9ea5-8940f34d3abd.png)

**Comment by paradigm** [comment]
Huh, interesting that the Linux kernel's `Makefile` uses `rsync` for a local copy.

I'll be sure to add `wget` and `rsync` to the list of dependencies.

**Comment by paradigm** [comment]
Fixed with 0.7.13
