### ISSUE TITLE
brl fetch void - tar invalid tar magic

### ISSUE THREAD

**Issue by GutsyHeart** [bedrocklinux/bedrocklinux-userland#160]
![tar invalid tar magic](https://i.imgur.com/lnyXnoS.png)

**Comment by nift4** [comment]
Did you try multiple times? Maybe broken download.

And what are your stratas (already fetched)?

**Comment by paradigm** [comment]
Void changed repository database compression from gzip to zstd.

`brl fetch` support for this was added in [beta channel](https://bedrocklinux.org/0.7/beta-channel.html) recently.  If you need to fetch Void now, consider jumping to the beta.  You can always switch back to the stable channel pretty easily once 0.7.14 becomes stable.

Alternatively, you can wait for this to hit stable.  The main blocker for release is corresponding documentation.  At this point in time I'm aiming to wrap doc changes and push them this weekend, although I cannot promise it will not slip further.

**Comment by GutsyHeart** [comment]
Thanks. Beta channel is working.

**Comment by paradigm** [comment]
Fixed in 0.7.14, closing.
