### ISSUE TITLE
Data Safety

### ISSUE THREAD

**Issue by Imperial-Industries** [bedrocklinux/bedrocklinux-userland#163]
So this is less of an issue and more of a question, I apologize in advanced.
I have nor hijacked my computer yet. I just wanted to know whether my computer would retain its files (like things I have in my home and Downloads folders) or not. Thank you in advance!

**Comment by paradigm** [comment]
Yes, your home and Downloads folder should be retained.

That having been said, I recommend first trying Bedrock out in a VM or spare machine and testing your expected workflow to confirm you don't run into any showstoppers.  Bedrock works very well for some workflows, but still has some rough corners that keep it from being suitable for everyone.  If that goes well, I recommend backing up before installing Bedrock on your production machine, just as one would do with any traditional distro.

**Comment by Imperial-Industries** [comment]
OK! Thank you for the swift reply!
