### ISSUE TITLE
Navigation Bar

### ISSUE THREAD

**Issue by Imperial-Industries** [bedrocklinux/bedrocklinux-userland#164]
This is my second "issue" (not really an issue). I apologize.
I have successfully install Bedrock onto my system and have installed packages from Arch Linux's AUR. What I'm wondering is whether or not there is a way to put an application installed through Arch's AUR onto my launcher menu. My base system is Ubuntu 18.04 using the MATE desktop environment.

**Comment by SeerLite** [comment]
This is supposed to work out of the box, but it seems like there is a bug on the current stable release that may cause issues on some launchers.
[According to paradigm on /r/bedrocklinux](https://www.reddit.com/r/bedrocklinux/comments/fsdkax/how_to_refresh_the_rofi_application_menu/fm8lb4z/), the latest beta should fix this. You could try it out and see if it works for you

**Comment by Imperial-Industries** [comment]
That worked! Thank you so much!
