### ISSUE TITLE
Networking on Arch

### ISSUE THREAD

**Issue by Imperial-Industries** [bedrocklinux/bedrocklinux-userland#166]
When I "boot" into Arch through the Bedrock Bootloader, everything seems to work fine. I start gnome and everything's great. Gnome says it's connected to the internet, so I open Firefox and type in a random link. Firefox says it's not connected to the internet. This happens in Chrome, Web, and Chromium as well. Plus, when I type in `Sudo pacman -Sy`, it gets errors due to a missing internet connection. Is there a way to resolve this?

**Comment by paradigm** [comment]
- Did you hijack Arch, install it via `brl fetch`, or install it via another means?
- Which strata provide the various things you're using to check the internet connection (e.g. Gnome, Firefox, Chromium, etc)?
- Does `ping -c1 8.8.4.4` give an error message or some `time=<number> ms` value?
- Does `for s in $(brl list); do strat $s wc -l /etc/resolv.conf; done` give error messages or a bunch of `<number> /etc/resolv.conf` lines?

**Comment by Imperial-Industries** [comment]
I installed it via brl fetch.
Ubuntu provides chrome and chromium.
Arch provides gnome, Firefox, and Web.
Ping responds with a network is unreachable error.
The last bit responds with a bunch of resolve.conf lines.

**Comment by paradigm** [comment]
Given:

- Bedrock does not currently make init configuration stuff work across strata.  It doesn't know how to, for example, teach Arch's init how to use Ubuntu's networking init configuration.
- `brl fetch` provides a minimal instance of a given distro.  Just enough to let users bootstrap whatever else they need.  It doesn't necessarily grab things like network setup automatically.

I suspect you just don't have your Arch init doing any networking setup.  The only counter point here is Gnome indicating it is connected to the internet.  I don't know enough about Gnome to understand why this would be the case when `ping` disagrees.

Try setting up Arch's networking.

- If you need internet access while doing so, you can reboot to another init that has a working network setup.  Presumably your hijacked stratum did and is still around.
- Arch's wiki is very good. Maybe start here: https://wiki.archlinux.org/index.php/Network_configuration
- Keep local vs global Bedrock stuff in mind.  If you need to edit an Arch specific file while doing this, prefix with `/bedrock/strata/arch/`.  Global files should be edited at their normal path.

**Comment by Imperial-Industries** [comment]
I actually figured it out!
First I had to activate Network Manager by `sudo NetworkManager`
Then I followed the steps in this link - https://www.digitalocean.com/community/questions/how-to-resolve-temporary-failure-in-name-resolution-issue

**Comment by paradigm** [comment]
Nicely done :)

**Comment by SeerLite** [comment]
Hey @Imperial-Industries, just wanted to chime in and say that in Arch, there's a specific systemd service file that manages NetworkManager. Running `sudo NetworkManager` may work, but is not the way it's supposed to be run under Arch as you'd be missing out on journal logs and daemon management.

A quick summary:
Use `systemctl start NetworkManager` to start NetworkManager, and `systemctl enable NetworkManager` in case you want to have it started on boot.

See [this section on how to use `systemctl` from the ArchWiki](https://wiki.archlinux.org/index.php/Systemd#Using_units) for more information.

**Comment by Imperial-Industries** [comment]
Oh ok.
Thank you!
