### ISSUE TITLE
Manjaro fails to install with brl-fetch

### ISSUE THREAD

**Issue by Titaniumtown** [bedrocklinux/bedrocklinux-userland#177]
When I run: `sudo brl fetch manjaro --mirror "mirror.dacentec.com/manjaro"`
It starts to install, but then I get:
```
/usr/bin/basestrap: line 84: mountpoint: command not found
==> Creating install root at /target-root
/usr/lib/manjaro-tools/util-mount.sh: line 128: mountpoint: command not found
/usr/lib/manjaro-tools/util-mount.sh: line 123: mount: command not found
==> ERROR: failed to setup API filesystems in new root
/usr/lib/manjaro-tools/util-mount.sh: line 173: umount: command not found
ERROR: Unexpected error occurred.
If you let brl-fetch automatically choose a mirror, it may have chosen a bad one.  Try manually providing a mirror with --mirror
```

Help?

**Comment by paradigm** [comment]
Looks like Manjaro changed around their dependencies.  Open up `/bedrock/share/brl-fetch/distros/manjaro` and add `util-linux` to [the bootstrap_deps list](https://github.com/bedrocklinux/bedrocklinux-userland/blob/e46c876f34572597fdda783fd9f62da7fa6ca515/src/slash-bedrock/share/brl-fetch/distros/manjaro#L74).

I'll queue this up for the next Bedrock release.

**Comment by Titaniumtown** [comment]
Thanks!

**Comment by Titaniumtown** [comment]
It works now with util-linux added

**Comment by Titaniumtown** [comment]
forgot to close this issue
