### ISSUE TITLE
InstantOS support

### ISSUE THREAD

**Issue by Titaniumtown** [bedrocklinux/bedrocklinux-userland#185]
I've been really wanting to test out instantOS on my laptop, but i dont want to wipe my hardrive and stuff, so i was wondering instantOS support could be implemented? It's arch linux based.

https://github.com/instantOS/instantOS
https://instantos.github.io/

**Comment by paradigm** [comment]
Bedrock as a project is greatly undermanned.  [We already support quite a few distros](https://bedrocklinux.org/0.7/distro-compatibility.html) but at some point we need to sleep.  We simply don't have the people-hours available to master and maintain Bedrock compatibility with every single distro out there.

[If you can find someone with the background, time, and interest to be a Bedrock InstantOS maintainer](https://bedrocklinux.org/contributing.html#distro-maintainer) I'd be happy to consider having them join the team.  Here isn't the place to find them; if such people existed here, they would already be doing the job.

**Comment by Titaniumtown** [comment]
Ok, I'll look into adding instantOS support. Keep an eye out for a pull request!

**Comment by Titaniumtown** [comment]
#186

**Comment by Titaniumtown** [comment]
I would love to be someone who actively works on this project @paradigm!

**Comment by paradigm** [comment]
> I would love to be someone who actively works on this project @paradigm!

Happy to hear it :)

Your submissions so far are things which add review overhead and maintenance burden but don't really push the project forward.  If you want them for your _own_ benefit, that's fine, but if your goal here is to contribute to the project's success, note that they're effectively a net drain on very limited resources.

Things you can do to help the project succeed can be found [here](https://bedrocklinux.org/contributing.html).  For example, you could work on researching and fixing [the grub/btrfs/zfs issue](https://bedrocklinux.org/0.7/feature-compatibility.html#grub-btrfs-zfs).  It's probably the most complained about open issue we have, and currently there is no one pursuing it.  It also doesn't really require a strong Bedrock background; it's not something that strictly needs my particular expertise, and so it's fitting to hand off.
