### ISSUE TITLE
Using DE from another stratum

### ISSUE THREAD

**Issue by Titaniumtown** [bedrocklinux/bedrocklinux-userland#191]
So I've been using instantOS (an arch based distro) that has it's own WM. I also want to switch to gentoo, is it possible for me to keep an instantOS stratum, and use the DE (through startx) but use gentoo as my init stratum?

Note: the instantOS related applications aren't available on gentoo yet

**Comment by paradigm** [comment]
https://bedrocklinux.org/0.7/feature-compatibility.html#desktop-environments

There's no automatic cross-stratum wiring between the init, DM, and DE.

If you can make that wiring yourself, e.g. configure `~/.xinitrc`, there are no known issues.
