### ISSUE TITLE
Environment variables are stored in the bedrock config file

### ISSUE THREAD

**Issue by cainy-a** [bedrocklinux/bedrocklinux-userland#222]
System environment variables are generally stored in `/etc/environment`, however bedrock resets this each boot and requires setting it in `/bedrock/etc/bedrock.conf`.

Wouldn't it make more sense to just keep `/etc/environment` stored in the `bedrock` stratum and not on any other strata?

**Comment by paradigm** [comment]
> System environment variables are generally stored in `/etc/environment`,

This is one of the many files typical Linux systems used to manipulate environment variables, yes.

> however bedrock resets this each boot and requires setting it in `/bedrock/etc/bedrock.conf`.

This is a known defect I plan to resolve in 0.8 Naga.  For the time being, the recommended work around is indeed to set one's desired variables in `bedrock.conf`.

> Wouldn't it make more sense to just keep `/etc/environment` stored in the `bedrock` stratum and not on any other strata?

I don't follow how this makes more.  More sense than what?  In what way?

**Comment by cainy-a** [comment]
> This is a known defect I plan to resolve in 0.8 Naga.

Oh sorry I misunderstood, I thought that was intentional
