### ISSUE TITLE
Hijack Android

### ISSUE THREAD

**Issue by juancarlospaco** [bedrocklinux/bedrocklinux-userland#223]
Would be nice and useful to hijack Android, like [Android_x86](https://www.android-x86.org), would that be considered/supported in the future?.

**Comment by paradigm** [comment]
[This is addressed in the FAQ](https://bedrocklinux.org/faq.html#other-os):

> The techniques Bedrock Linux utilizes are fairly specific to Linux. While it may be possible to create a similar meta-distro for other kernels, they would require substantial new R&D and are not being pursued by anyone on the Bedrock Linux team.
> 
> While Android does use the Linux kernel, its userland is sufficiently distant that it, too, would require substantial R&D and is not currently being pursued.
