### ISSUE TITLE
i686 installer only prints help page

### ISSUE THREAD

**Issue by bcskillings** [bedrocklinux/bedrocklinux-userland#229]
I’m attempting to install Bedrock using the iSH app on my iPhone 12 Pro. While the phone is armv8, the iSH architecture (according to neofetch) runs as i686.

I downloaded the installer and went to run it with --hyjack, but doing so resulted in it printing the help page. I tried to specify the original stratum (alpine) but it resulted the same way. To test, I downloaded the x86_64 installer and it began to run but would not recognize that fuse was installed.

![9C3C10B1-8238-424C-98FA-8664977B3798](https://user-images.githubusercontent.com/31419498/120260014-a110a580-c25a-11eb-85da-774c07a49cbb.jpeg)

**Comment by bcskillings** [comment]
Just noticed my spelling error 🤦🏼

**Comment by JuPlutonic** [comment]
From project's gh-page-faq:

```
Q: Why does iSH emulate at all? Can't it use a JIT compiler, or virtualization?
A: iOS devices lack support for hardware virtualization
```

So, bedrock hijacking inside iSH(x86 emulation program) and in near future(take the pulse of new features of iPhone processors)on iPhones is impossible.
