### ISSUE TITLE
Why do I have such big performace drop when on bedrock linux?

### ISSUE THREAD

**Issue by TruncatedDinosour** [bedrocklinux/bedrocklinux-userland#232]
## Issue

Hello, I converted arch to bedrock just a few hours ago and what I noticed is that I got a huge drop in performace, why is that?

Well the performace drop is noticable for the first like 10 minutes of the boot, but why does that even happen, I'd like to fix it, but where?

And on poweroff, reboot or shutdown i get these errors:
![image](https://user-images.githubusercontent.com/71613062/126932528-df98a3f2-5346-4423-9309-37d98e27d990.png)

Maybe they have something to do in the performace drop? Maybe other users have expierienced it, if you have, how did you fix it?

## Version
Bedrock Linux 0.7.21 Poki

## Init system
SystemD

## Converted from
Arch linux -> Bedrock

**Comment by TruncatedDinosour** [comment]
## Found something intresting
the `systemd-update-utmp.service` service was failing, so this this is what I did:
```
sudo systemctl start systemd-update-utmp.service

sudo systemctl enable systemd-update-utmp.service

reboot
```

and as it looks like I have gotten some performace back, still is performing slower than usual, but better :)

**Comment by paradigm** [comment]
Can you go into detail on the characteristics of the performance drop?

**Comment by TruncatedDinosour** [comment]
> Can you go into detail on the characteristics of the performance drop?

slow command execution, programs start slower, slower graphics/stuff takes longer to render

**Comment by paradigm** [comment]
Bedrock adds overhead to file access from `/etc` and a new `/bedrock/cross` directory that programs are configured to look at (e.g. it is added to the `$PATH`).  This can slow down _some_ things those which make excessive use of the previous two mentioned directories.  For example, a ways back we found KDE's window manager was excessively reading from `/etc/localtime` which meant dragging windows around had lower performance.  (KDE promptly fixed this when we brought it to their attention.)

However, my understanding of Bedrock's overhead cannot explain _everything_ running slower, starting slower, and rendering slower.  I'm at a complete loss from your broad description of the problem at hand.

**Comment by TruncatedDinosour** [comment]
> Bedrock adds overhead to file access from `/etc` and a new `/bedrock/cross` directory that programs are configured to look at (e.g. it is added to the `$PATH`). This can slow down _some_ things those which make excessive use of the previous two mentioned directories. For example, a ways back we found KDE's window manager was excessively reading from `/etc/localtime` which meant dragging windows around had lower performance. (KDE promptly fixed this when we brought it to their attention.)
> 
> However, my understanding of Bedrock's overhead cannot explain _everything_ running slower, starting slower, and rendering slower. I'm at a complete loss from your broad description of the problem at hand.

Hm, I don't know, I reaslly noticed a big performace drop. But it might just have been my hardware heh

**Comment by paradigm** [comment]
Your hardware may explain why the normally negligible overhead for `/etc` and `/bedrock/cross` would be noticeable in the specific, select scenarios where those arise.

Your hardware does not explain why things Bedrock has nothing to do with show a performance difference when Bedrock is in play.

**Comment by TruncatedDinosour** [comment]
> Your hardware may explain why the normally negligible overhead for `/etc` and `/bedrock/cross` would be noticeable in the specific, select scenarios where those arise. However, again, that would only affect _some_ software. Your hardware wouldn't explain why _everything_ runs slower, starts slower, and renders slower. Most processes run and start and render without hitting `/etc` or `/bedrock/cross` very much if at all.

Yeah, I'm as confused as you, my system became slower, the resource usage wasn't even affected or anything, but now I am back no vanilla arch linux, I will test bedrock in a VM and I will see if the same thing happens

**Comment by TruncatedDinosour** [comment]
> > Your hardware may explain why the normally negligible overhead for `/etc` and `/bedrock/cross` would be noticeable in the specific, select scenarios where those arise. However, again, that would only affect _some_ software. Your hardware wouldn't explain why _everything_ runs slower, starts slower, and renders slower. Most processes run and start and render without hitting `/etc` or `/bedrock/cross` very much if at all.
> 
> Yeah, I'm as confused as you, my system became slower, the resource usage wasn't even affected or anything, but now I am back on vanilla arch linux, I will test bedrock in a VM and I will see if the same thing happens

Update: it is causing the same issues like before

**Comment by TruncatedDinosour** [comment]
> > Your hardware may explain why the normally negligible overhead for `/etc` and `/bedrock/cross` would be noticeable in the specific, select scenarios where those arise. However, again, that would only affect _some_ software. Your hardware wouldn't explain why _everything_ runs slower, starts slower, and renders slower. Most processes run and start and render without hitting `/etc` or `/bedrock/cross` very much if at all.
> 
> Yeah, I'm as confused as you, my system became slower, the resource usage wasn't even affected or anything, but now I am back on vanilla arch linux, I will test bedrock in a VM and I will see if the same thing happens

Update: It is causing the same issues, but some programs seem to have not been affected, not mainly firefox, lightdm and cinnamon are being affected in the VM, other apps seem to be better than on my real hardware

**Comment by TruncatedDinosour** [comment]
> > > Your hardware may explain why the normally negligible overhead for `/etc` and `/bedrock/cross` would be noticeable in the specific, select scenarios where those arise. However, again, that would only affect _some_ software. Your hardware wouldn't explain why _everything_ runs slower, starts slower, and renders slower. Most processes run and start and render without hitting `/etc` or `/bedrock/cross` very much if at all.
> > 
> > 
> > Yeah, I'm as confused as you, my system became slower, the resource usage wasn't even affected or anything, but now I am back on vanilla arch linux, I will test bedrock in a VM and I will see if the same thing happens
> 
> Update: It is causing the same issues, but some programs seem to have not been affected, not mainly firefox, lightdm and cinnamon are being affected in the VM, other apps seem to be better than on my real hardware

Okay, it definally was my hardware, now after using the VM for half an hour everything in performing fine, though I wonder what caused it on my hardware, should I close this issue?

**Comment by paradigm** [comment]
I am completely, totally bewildered as to why Bedrock would have performance issues on native hardware that it does not present in a VM.

If you think you have a lead we can use to debug what's going on and fix it, do feel free to leave this issue open so we can keep working at it.  Otherwise, if we don't have any leads, I don't see value in leaving the issue open.

**Comment by TruncatedDinosour** [comment]
> I am completely, totally bewildered as to why Bedrock would have performance issues on native hardware that it does not present in a VM.
> 
> If you think you have a lead we can use to debug what's going on and fix it, do feel free to leave this issue open so we can keep working at it. Otherwise, if we don't have any leads, I don't see value in leaving the issue open.

Yeah, I think it was just my hardware, I don't know, but most people seem to be fine, so I don't think we need to keep this issue open haha, thanks for the help and have a nice day :)

**Comment by paradigm** [comment]
Happy to help, you also have a nice day :)
