### ISSUE TITLE
brl fetch doesn't work with gentoo

### ISSUE THREAD

**Issue by kskeigrshi** [bedrocklinux/bedrocklinux-userland#244]
![image](https://user-images.githubusercontent.com/90227297/146387201-8e4c0d6a-a5f6-41d6-9746-0edf1b065514.png)
I've tried this a few times with different servers, and `brl fetch` just doesn't seem to like gentoo. I've never even touched Gentoo before, so I don't know where `brl` searches for when 'finding bootstrap software' for Gentoo.

**Comment by paradigm** [comment]
Gentoo recently made changes which broke `brl fetch`.  I have a fix in master that will trickle down to the next beta and stable release.

For the time being, open up `/bedrock/share/brl-fetch/distros/gentoo` with root permissions and either manually apply [the changes shown here](https://github.com/bedrocklinux/bedrocklinux-userland/commit/cd943299058a6a305aae64e63c156367698d6f86) or just outright overwrite the file with the [this](https://github.com/bedrocklinux/bedrocklinux-userland/blob/cd943299058a6a305aae64e63c156367698d6f86/src/slash-bedrock/share/brl-fetch/distros/gentoo) (make sure to click "Raw").

**Comment by paradigm** [comment]
Should be fixed in 0.7.25

**Comment by kskeigrshi** [comment]
As far as I have tested, it does. Thanks for the fix.
