### ISSUE TITLE
Arch linux fetch is broken? 

### ISSUE THREAD

**Issue by Naia-love** [bedrocklinux/bedrocklinux-userland#253]
I just installed bedrock linux on a fresh void-musl install (with only plasma and firefox installed more basically), everything went fine with the bedrock hijack, the tutorial worked well, as so the install of another void strata and an alpine one, but when I tried to install an arch strata, I get this error (note that it tried a few differents mirror, i tried specifing myself one of the T1 mirror but still got this error.)

```
➜  ~ sudo brl fetch arch arch
[ 1/19 (  5%)] Determining name
* Using arch
[ 2/19 ( 10%)] Determining CPU architecture
* Using x86_64
[ 3/19 ( 15%)] Determining release
* Using rolling
[ 4/19 ( 21%)] Determining mirror
* Checking bedrock.conf [brl-fetch-mirror] items
[\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\] 100%
* Fast filtering 257 to top 10
[\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\] 100%
* Finding fastest mirror from 10
[\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\] 100%
* Using https://de.arch.mirror.kescher.at/
[ 5/19 ( 26%)] Making bootstrap directory structure
[ 6/19 ( 31%)] Downloading package information database
Downloading https://de.arch.mirror.kescher.at//core/os/x86_64/core.db.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  133k  100  133k    0     0   308k      0 --:--:-- --:--:-- --:--:--  308k
Downloading https://de.arch.mirror.kescher.at//extra/os/x86_64/extra.db.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 1543k  100 1543k    0     0   620k      0  0:00:02  0:00:02 --:--:--  621k
[ 7/19 ( 36%)] Decompressing package information database
[\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\] 100%
[ 8/19 ( 42%)] Converting distro package information database to brl format
[\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\] 100%
[ 9/19 ( 47%)] Calculating required bootstrap packages
[/  |  \  -  /  |  \  -  /  |  \ ]  ??%Unable to find provider for "tpm2-tss"
[\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\] 100%
ERROR: Unexpected error occurred.
This is commonly due to distro mirror layout changes breaking `brl fetch`.  Possible solutions:
- If you did not, consider manually providing a mirror with --mirror
- Check for a Bedrock Linux update with `brl update`
- Check for a Bedrock Linux beta which may contain a fix
- Try `brl import` which does not rely on mirror layout
```

**Comment by MIracleyin** [comment]
i meet the same problem for now

**Comment by MIracleyin** [comment]
I meet the same problem for arch-arm

**Comment by paradigm** [comment]
I pushed 0.7.27beta1 which includes a fix.  [Consider trying the beta](https://bedrocklinux.org/0.7/beta-channel.html) if you need the functionality before it hits stable.

**Comment by MIracleyin** [comment]
thx for your work.

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Daniel Thau ***@***.***>
发送时间: Thursday, March 3, 2022 8:56:24 AM
收件人: bedrocklinux/bedrocklinux-userland ***@***.***>
抄送: Miracle Yin ***@***.***>; Comment ***@***.***>
主题: Re: [bedrocklinux/bedrocklinux-userland] Arch linux fetch is broken? (Issue #253)


I pushed 0.7.27beta1 which includes a fix. Consider trying the beta<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fbedrocklinux.org%2F0.7%2Fbeta-channel.html&data=04%7C01%7C%7C71a5133a8aba483f59dc08d9fcb0a42c%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637818657883413665%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=Kf5PLJSwaj9PwLlcus8hSiEZ4D0OAhf7Qa0y6ws%2BTG4%3D&reserved=0> if you need the functionality before it hits stable.

―

**Comment by paradigm** [comment]
You are welcome :)

**Comment by Naia-love** [comment]
yea thanks a lot! i tried to apply your patch myself (before you pushed the beta release) and it worked fine. 
I'm very much enjoying bedrock so far, it's really nice, gg for all your hard work

**Comment by paradigm** [comment]
FWIW, just pushed 0.7.27 to stable with this fix.
