### ISSUE TITLE
Chrome OS (Flex) based bedrock linux

### ISSUE THREAD

**Issue by lavilao** [bedrocklinux/bedrocklinux-userland#258]
Hello has anyone tried to use a Chrome OS Flex hijacked system? I have been reading the reddit pages recently (new to the community btw) and have found no one has tried so I wanted to ask here (there were attempts with Chrome OS but never were continued beyond imagination). Also cheers to the devs for creating this wonderfull meta distro!

**Comment by paradigm** [comment]
Findings on how well distros play with Bedrock are documented [here](https://bedrocklinux.org/0.7/distro-compatibility.html).  If you don't see a distro there, the answer is probably that there haven't been a meaningful number of people trying it.  Given the lack of others trying it, best way to find out how well it works is to try it out yourself in a test environment like a VM.

**Comment by lavilao** [comment]
thanks for the info
