### ISSUE TITLE
Question / "possible bug (probably me being a bit stupid)"

### ISSUE THREAD

**Issue by jamesbt365** [bedrocklinux/bedrocklinux-userland#262]
i have a few questions regarding btrfs with grub and bedrock, i get it confuses it, so i'm using a ext4 root and a btrfs home, but it still complains, but surely in the grub config my home partition should never be mentioned anyway, so therefore there should be no issues right? I'm not sure as i haven't tried out bedrock at all.

Yet i still get this:
![image](https://user-images.githubusercontent.com/22662856/164338131-14ede73b-6f11-4cc8-a9d3-030f0822b82e.png)
surely its okay to go ahead anyway (may need to modify the sh myself a bit if its not going to break anything with my system)

Here is my fstab:
![image](https://user-images.githubusercontent.com/22662856/164338369-d9ebee06-7d63-4d01-96c9-b8de84bded94.png)
You can see that my root is ext4, but my home is btrfs. Also does it matter that i'm using LUKS? Will that fuck me over later?

So is this intended,' would there be issues if i just (try but probably fail) to remove the locks from the sh (though i'm literally the most stupid fuck on the planet to even do so) and install bedrock anyway?

(This is currently a gentoo install as well, if that matters.)

Sorry if this is worded really poorly.

**Comment by paradigm** [comment]
The sanity check appears to be working as intended.  As noted in the error message, the setup you are describing is not supported over concerns that it will trigger buggy behavior in GRUB.

If you are confident you understand the issue, and that your setup avoids it, and you're accepting of the fact that it will be your fault if things explode as a result of your action, there's nothing else to stop you from disabling the sanity check in the hijack script.  Nothing else in Bedrock's code or nature cares about this; the check is entirely to avoid a known bug in GRUB.  If you do edit the script, be sure to use a null-safe editor.  Just search for `grub` and you'll find the checks to comment out or remove.

**Comment by jamesbt365** [comment]
Alright thank you, i don't see anything referencing my home partition in the grub configuration so i should just be able to edit the script then, thank you for answering my question. If it does go wrong then i'll probably just have to mount my home manually every time but i can manage with that.
