### ISSUE TITLE
due to: unable to find file (ENOENT)

### ISSUE THREAD

**Issue by unimado1** [bedrocklinux/bedrocklinux-userland#265]
### What's the problem?

When I tried to install _yay_ on _arch_ stratum, I ran into a problem: after I installed _git_ and _base-devel_ packages, **I tried to cd into yay directory, but only got this error message:** 

![изображение](https://user-images.githubusercontent.com/104565294/165750558-cf89e962-6f28-4aa2-9789-a126604f3848.png)

![изображение](https://user-images.githubusercontent.com/104565294/165749608-464512fd-204f-45a4-b715-ce2197f03e6e.png)

Soon later, I tried to run _bauh_ AppImage from _arch_ stratum, but I came across a similar error, but this time I discovered, that _arch_ stratum just can't read this mountpoint:

![изображение](https://user-images.githubusercontent.com/104565294/165744361-fa745f48-9638-4230-b0ce-4aa1806c2f53.png)

I'm running Bedrock Linux 0.7.27 Poki x86_64 installed from Void Linux

![изображение](https://user-images.githubusercontent.com/104565294/165746173-13055807-3b6c-4758-a668-2821e7f7f8de.png)

I will be **_very glad_** if **someone** helps me with this difficult (at least for me) problem. Best wishes!

**Comment by SolitudeSF** [comment]
`sudo strat arch cd directory` is just a wrong command. it will fail everywhere. `sudo` executes a program, but `cd` is a shell builtin.

**Comment by SolitudeSF** [comment]
and your appimage fails because you dont have mesa installed in arch stratum.

**Comment by unimado1** [comment]
Thanks so much for the help! =)
