### ISSUE TITLE
brl mirror is broken for 32bit users, cant install package managers

### ISSUE THREAD

**Issue by coreybruce** [bedrocklinux/bedrocklinux-userland#266]
Hey just wanted to report that fetching seems to be broken for 32bit users, here is my log of my trying to install Arch-32. I also tried to install fedora and ran into the same issue.

I am using Debian 11 Buster i686

```
corey@corey-FujistuLifeBook:~$ sudo brl fetch arch-32
[ 1/19 (  5%)] Determining name
* Using arch-32
[ 2/19 ( 10%)] Determining CPU architecture
* Using i686
[ 3/19 ( 15%)] Determining release
* Using rolling
[ 4/19 ( 21%)] Determining mirror
* Checking bedrock.conf [brl-fetch-mirror] items
[\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\] 100%
ERROR: Unable to automatically find a valid mirror.  Manually specify mirror with `--mirror`.
ERROR: Unexpected error occurred.
This is commonly due to distro mirror layout changes breaking `brl fetch`.  Possible solutions:
- If you did not, consider manually providing a mirror with --mirror
- Check for a Bedrock Linux update with `brl update`
- Check for a Bedrock Linux beta which may contain a fix
- Try `brl import` which does not rely on mirror layout
```

**Comment by coreybruce** [comment]
> I can't reproduce the issue; I was able to `brl fetch` i686 instances of both Arch Linux 32 and Fedora.
> 
> > here is my log of my trying to install Arch-32.
> 
> `brl fetch`'s ability to automatically determine a good mirror is inconsistent, and thus sometimes users need to find and provide a good mirror manually. This is indicated in the error message you copy/pasted but did not address. [Did you provide `brl fetch` a known good i686 Arch Linux 32 package mirror?](https://archlinux32.org/mirrorlist/)
> 
> > I also tried to install fedora and ran into the same issue.
> 
> [Did you specify a Fedora release which supports i686?](https://fedoramagazine.org/in-fedora-31-32-bit-i686-is-86ed/)

Hmm I see and do you need to provide the mirror yourself or does the script need to be updated with the new mirror?

**Comment by paradigm** [comment]
> Hmm I see and do you need to provide the mirror yourself or does the script need to be updated with the new mirror?

The error message you copied and pasted into this thread but continue to fail to address is to manually provide a mirror with the `--mirror` flag.

**Comment by coreybruce** [comment]
Oh ok I didn't see any documentation about needing to do that, I thought the script would do all this for the user when setting up the other package managers

**Comment by paradigm** [comment]
> Oh ok I didn't see any documentation about needing to do that,

It's mentioned in the error message you copied and pasted for me that I've already pointed out to you twice before that you continue to fail to address.  I don't know if you _read_ it, but you almost certainly _saw_ it.

It's also covered in `brl tutorial brl-fetch` and [the basic usage documentation](https://bedrocklinux.org/0.7/basic-usage.html) and [the `brl-fetch` specific documentation](https://bedrocklinux.org/0.7/commands.html#brl-fetch).

> I thought the script would do all this for the user when setting up the other package managers

Things like searching forums or contacting distro developers to understand why their advertised mirrors aren't working would require some kind of artificial intelligence well beyond the scope of Bedrock Linux.

**Comment by coreybruce** [comment]
brl tutorial brl-fetch deosn't cover Arch or Arch32, only Fedora and another one I can't remember the name of also there is no documention I could see about needing to manually configure a mirror for Arch/Arch32

**Comment by paradigm** [comment]
I have thus far pointed you to five different sources of information about the issue you've ran into and how to respond to it:

- The very error message you copy/pasted to me.  I don't understand why you keep failing to register or acknowledge its existence.
- My own explanation in this thread, independent of proceeding documentation.
- `brl tutorial brl-fetch`
- https://bedrocklinux.org/0.7/basic-usage.html
- https://bedrocklinux.org/0.7/commands.html#brl-fetch

These all describe the issue in various levels of detail, and these all tell you how to respond to it.  I find your continued assertion that this situation isn't covered in documentation after this bewildering.  While in principle I'd like to help, I'm at a complete loss on how to proceed at this point, and am inclined to throw in the towel.
