### ISSUE TITLE
cant fetch archlinux

### ISSUE THREAD

**Issue by lavilao** [bedrocklinux/bedrocklinux-userland#273]
Hi, I recently installed bedrocklinux 0.7.27 and everytime I tried to fetch archlinux it would throw this error ```The keyring file /usr/share/pacman/keyrings/archlinux.gpg does not exist``` and cancel the installation. Is this a known issue? is it fixed on the 0.7.28 beta? thanks in advice.

**Comment by lavilao** [comment]
According to Reddit the issue is also in the 0.7.28 beta

**Comment by paradigm** [comment]
[It's fixed in master](https://github.com/bedrocklinux/bedrocklinux-userland/commit/5889b825fe50fb77c83fa94575726ac764649a56) and is something you should be able to apply locally to `/bedrock/share/brl-fetch/distros/arch` to unblock yourself here.

I'm really hoping to push this to a beta, if not a stable release, this weekend.  However, I have some competing time constraints and that goal may slip.

**Comment by lavilao** [comment]
Thank You! Question, to be able to brl update to a beta must I be on a beta versión of bedrocklinux? Cuz I tried to upgrade 0.7.27 to 0.7.28 beta but it said there was not any update available

**Comment by paradigm** [comment]
> Thank You!

You're welcome :)

> Question, to be able to brl update to a beta must I be on a beta versión of bedrocklinux?  Cuz I tried to upgrade 0.7.27 to 0.7.28 beta but it said there was not any update available

No, you can update to a beta from any release.  It doesn't actually understand the concept of a beta under-the-hood.  Rather, `brl update` just updates to the newest release it finds in the configured mirror list.  If the newest release in the mirror list is a beta, it'll update to a beta.

Did you follow [the documentation](https://bedrocklinux.org/0.7/beta-channel.html)?

**Comment by lavilao** [comment]
Weird, I used brl update from 0.7.27 and it said no update detectes🤔

**Comment by paradigm** [comment]
> This also needs to be fixed in artix (`artix-keychain`).

[Applied in master](https://github.com/bedrocklinux/bedrocklinux-userland/commit/e610db35afe2c4d93b31f8a353d52c182c7a331e).  The same change was needed for Arch Linux ARM but, strangely, not for Arch Linux 32.  Maybe the latter project is lagging here and will need an update later.  I preemptively applied it for Arch Linux 32, as it didn't really hurt.

**Comment by paradigm** [comment]
Ah, I changed it locally but forgot to include it in the commit.  [Fixed as well](https://github.com/bedrocklinux/bedrocklinux-userland/commit/097a10a58aab2b617c5c3f43fb7e0bc3ff09824d), good eye.

**Comment by agnosticlines** [comment]
Hi,

Found this issue while searching for the error I got, seems like it's still broken on the latest bedrock linux with `arch-arm`?

Not sure if I'm doing something wrong

```
[13/19 ( 68%)] Configuring
==> ERROR: The keyring file /usr/share/pacman/keyrings/archlinuxarm.gpg does not exist.
ERROR: Unexpected error occurred.
This is commonly due to distro mirror layout changes breaking `brl fetch`.  Possible solutions:                                                           
- If you did not, consider manually providing a mirror with --mirror         
- Check for a Bedrock Linux update with `brl update`                         
- Check for a Bedrock Linux beta which may contain a fix                     
- Try `brl import` which does not rely on mirror layout                      
```

Tried the `--mirror` option too, and it looks like my arch-arm strata has the fix included? but still giving the same error

```
LC_ALL=C chroot "${1}" /usr/bin/pacman-key --populate archlinuxarm
bootstrap_deps="arch-install-scripts archlinuxarm-keyring"
```

Version: 

```
# brl version                                                              
Bedrock Linux 0.7.28 Poki
```

**Comment by paradigm** [comment]
The original issue which hit:

- Arch Linux
- Arch Linux 32
- Arch Linux ARM
- Artix

was that the `arch-install-scripts` package no longer indicated it was dependent on the corresponding `*-keyring` package.

Apparently, Arch Linux ARM also had an additional change where `base` no longer depended on the `archlinuxarm-keyring` package.  I missed this in testing,  myopic just about the `arch-install-scripts` package.

[I've pushed a fix to master](https://github.com/bedrocklinux/bedrocklinux-userland/commit/8c3ccca38dc4ea84a540f0365e14dc7c69ce75db) that you should be able to apply manually to `/bedrock/share/brl-fetch/distros/arch-arm` for the time being.  It should filter down to the next beta/stable releases accordingly.
