### ISSUE TITLE
A bit confused about how the init system works

### ISSUE THREAD

**Issue by Goproxer** [bedrocklinux/bedrocklinux-userland#274]
I hijacked void and fetched an artix stratum. Originally after installing plasma using xbps I used `ln -s /etc/sv/sddm/ /var/service/` to create a runit autostart. But when I chose the artix runit then sddm would not start. I know it's working as intended but when I looked into `/var`, the service folder does not exist anymore. I rebooted into the void stratum and found the same thing but sddm started on that stratum. The system works fine, but how did bedrock handle the init process exactly and can I still add runit services the same way as before? Help appreciated   :)
(New to both runit and bedrock, hope it's not a dumb question)

**Comment by paradigm** [comment]
You seem to be missing fundamental Bedrock concepts.  Please go through either the interactive tutorial via `brl tutorial basics` or [read the basic usage documentation](https://bedrocklinux.org/0.7/basic-usage.html).  While you should try to learn everything there, at a minimum focus on the concept of _local paths_ vs _global paths_.

**Comment by Goproxer** [comment]
> You seem to be missing fundamental Bedrock concepts.  Please go through either the interactive tutorial via `brl tutorial basics` or [read the basic usage documentation](https://bedrocklinux.org/0.7/basic-usage.html).  While you should try to learn everything there, at a minimum focus on the concept of _local paths_ vs _global paths_.
> 


I guess so :) The mirror was too slow so I skipped most of the tutorial. Too bad there wasn't some kind of static tutorial like vimtutor :(
