### ISSUE TITLE
can't fetch arch

### ISSUE THREAD

**Issue by darkmaxoff** [bedrocklinux/bedrocklinux-userland#287]
i use some linux based on rosa and install Bedrock and when i try to fetch arch i see error. on usually this gave me this: 
mostesttest ~ # brl fetch -n tut-arch arch
[ 1/19 (  5%)] Determining name
* Using tut-arch
[ 2/19 ( 10%)] Determining CPU architecture
* Using x86_64
[ 3/19 ( 15%)] Determining release
* Using rolling
[ 4/19 ( 21%)] Determining mirror
* Checking bedrock.conf [brl-fetch-mirror] items
[\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\] 100%
* Fast filtering 309 to top 10
[\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\] 100%
Fast filter failed, falling back to slow method against all 309 mirrors.
This is known to fail within certain virtualization environments which do not support ICMP.
If this seems unacceptably slow, ctrl-c out, brl remove the stratum, then look up a good mirror for the distro and brl fetch again, this time manually providing mirror with -m
* Finding fastest mirror from 309
[\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\] 100%
* Using https://archive-ru-mos.gaab-networks.de/arch/
[ 5/19 ( 26%)] Making bootstrap directory structure
[ 6/19 ( 31%)] Downloading package information database
Downloading https://archive-ru-mos.gaab-networks.de/arch//core/os/x86_64/core.db.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  132k  100  132k    0     0   931k      0 --:--:-- --:--:-- --:--:--  937k
Downloading https://archive-ru-mos.gaab-networks.de/arch//extra/os/x86_64/extra.db.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 8491k  100 8491k    0     0  2374k      0  0:00:03  0:00:03 --:--:-- 2374k
Downloading https://archive-ru-mos.gaab-networks.de/arch//community/os/x86_64/community.db.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    45  100    45    0     0    142      0 --:--:-- --:--:-- --:--:--   141
[ 7/19 ( 36%)] Decompressing package information database
[\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\] 100%
[ 8/19 ( 42%)] Converting distro package information database to brl format
/bedrock/libexec/brl-fetch: line 711: can't create community/*/ALL: nonexistent directory
[\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\] 100%
ERROR: Unexpected error occurred.
This is commonly due to distro mirror layout changes breaking `brl fetch`.  Possible solutions:
- If you did not, consider manually providing a mirror with --mirror
- Check for a Bedrock Linux update with `brl update`
- Check for a Bedrock Linux beta which may contain a fix
- Try `brl import` which does not rely on mirror layout

but if i manually pick mirror they give me this: 
mostesttest ~ # brl fetch -n tut-arch arch -m http://mirror.i3d.net/pub/archlinux/
[ 1/19 (  5%)] Determining name
* Using tut-arch
[ 2/19 ( 10%)] Determining CPU architecture
* Using x86_64
[ 3/19 ( 15%)] Determining release
* Using rolling
[ 4/19 ( 21%)] Determining mirror
* Using http://mirror.i3d.net/pub/archlinux/
[ 5/19 ( 26%)] Making bootstrap directory structure
[ 6/19 ( 31%)] Downloading package information database
Downloading http://mirror.i3d.net/pub/archlinux//core/os/x86_64/core.db.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  132k  100  132k    0     0   189k      0 --:--:-- --:--:-- --:--:-- 1778k
Downloading http://mirror.i3d.net/pub/archlinux//extra/os/x86_64/extra.db.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 8491k  100 8491k    0     0  11.7M      0 --:--:-- --:--:-- --:--:-- 11.7M
Downloading http://mirror.i3d.net/pub/archlinux//community/os/x86_64/community.db.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    45  100    45    0     0    215      0 --:--:-- --:--:-- --:--:--     0
[ 7/19 ( 36%)] Decompressing package information database
[\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\] 100%
[ 8/19 ( 42%)] Converting distro package information database to brl format
/bedrock/libexec/brl-fetch: line 711: can't create community/*/ALL: nonexistent directory
[\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\] 100%
ERROR: Unexpected error occurred.
This is commonly due to distro mirror layout changes breaking `brl fetch`.  Possible solutions:
- If you did not, consider manually providing a mirror with --mirror
- Check for a Bedrock Linux update with `brl update`
- Check for a Bedrock Linux beta which may contain a fix
- Try `brl import` which does not rely on mirror layout

**Comment by kumquat-ir** [comment]
This is because Arch has merged the `community` repository into the `extra` repository, as noted in these blog posts:
https://archlinux.org/news/git-migration-announcement/
https://archlinux.org/news/git-migration-completed/

The only thing that would likely need to be done to fix this is removing references to `community` in the fetch script

**Comment by darkmaxoff** [comment]
> This is because Arch has merged the `community` repository into the `extra` repository, as noted in these blog posts: https://archlinux.org/news/git-migration-announcement/ https://archlinux.org/news/git-migration-completed/
> 
> The only thing that would likely need to be done to fix this is removing references to `community` in the fetch script

thx it worked

**Comment by darkmaxoff** [comment]
if somebody have that  trouble just comment all lines with `community` in file on screenshot 
![image](https://github.com/bedrocklinux/bedrocklinux-userland/assets/38246516/acf7eaa5-c943-4c77-b0c6-0a94319d94d1)
