### ISSUE TITLE
pre-brt installer

### ISSUE THREAD

**Issue by paradigm** [bedrocklinux/bedrocklinux-userland#29]
Plans/thoughts for/on the Bedrock Linux installer:

Bedrock Linux, as a project, is about leveraging pre-existing software.  Philosophically, we try to avoid re-inventing the wheel if we can just use some other distro's solution instead.  Installation is no exception: plenty of other distros already provide live system images which could be used to install Bedrock Linux; there is no need for Bedrock Linux to have its own branded live system image for an installer.  Instead, we'll portable installation software that can run on some other distro (or another instance of Bedrock Linux), be it a live cd, an installation on another partition, or even [changing an existing installation of another distro into Bedrock Linux](https://github.com/bedrocklinux/bedrocklinux-userland/issues/28).

Moreover, the project tries to maximize choice.  If users want to install with some obscure live cd, that should be an option if we can make it one.  The installation software should be as portable as we can make it.  No relying on GNUisms - if a user wants to install with a busybox-based system, we should support it.  Note that utilizing GNUisms for non-essential functionality is fine (e.g. GNU tar auto-detecting and auto-decompressing compressed tarballs, so long portable as alternatives exist for the essentials.  Given the portability requirement, an installer cannot require a GUI.  In general, smaller code bases are preferable; whether or not to allow an alternative GUI installer (maybe a wrapper around the CLI installer) has not yet been decided.

A long-term goal is to have an [updater](https://github.com/bedrocklinux/bedrocklinux-userland/issues/12).  Due to the design discussed there, it will need to be source-based.  For the time being, the installer should also be source-based (i.e. we won't distribute binaries) in order to aid testing for what will eventually become a dual installer/updater.

In addition to being able to install a fresh system on newly formatted partitions, the installer should be able to [convert an existing non-Bedrock install into Bedrock Linux](https://github.com/bedrocklinux/bedrocklinux-userland/issues/28).  In addition to being able to do it in-place, we should investigate having the installer be able to kick out packages (.debs, .rpms, etc).

**Comment by Sepero** [comment]
+1
Debian and Centos both provide great stable systems with long term support which may provide a perfect base system for Bedrock.

**Comment by paradigm** [comment]
Done in Poki
