### ISSUE TITLE
Void Linux fetch broken

### ISSUE THREAD

**Issue by NopeNopeGuy** [bedrocklinux/bedrocklinux-userland#300]
brl fetch void doesn't work
![image](https://github.com/bedrocklinux/bedrocklinux-userland/assets/132055572/7a65cb4b-2e2d-4a02-8ad7-80d9afaf26a7)

**Comment by EurobeatEnjoyer** [comment]
You can try using by specifying a mirror.  This should work for now:
`brl fetch -n tut-void void -m https://repo-de.voidlinux.org/`

**Comment by willem640** [comment]
I believe this was fixed by 56ed2b9

**Comment by paradigm** [comment]
Fixed in the recently released 0.7.30
