### ISSUE TITLE
/etc/init.d/rcK.clients brc command not found

### ISSUE THREAD

**Issue by cognhuepan** [bedrocklinux/bedrocklinux-userland#32]
I've added the following line to the end of my /etc/init.d/rcK.clients:

```
brc debian service networking start
```

and when the system is shutting down I get this message:

```
[ -- ]Running clients shutdown script... /etc/init.d/rK.clients: line 10: brc: not found
```

I've tried with

```
brc debian /etc/init.d/networking start
```

and got the same results.

**Comment by paradigm** [comment]
Poki no longer has its own init system for which this would be valid.
