### ISSUE TITLE
Compile issues with busybox 1_24_stable

### ISSUE THREAD

**Issue by DevPump** [bedrocklinux/bedrocklinux-userland#43]
CC      libbb/messages.o
libbb/messages.c:59:4: error: #error unknown path to wtmp file
 #  error unknown path to wtmp file
    ^
libbb/messages.c:66:1: error: expected expression before ‘char’
 char bb_common_bufsiz1[COMMON_BUFSIZE] ALIGNED(sizeof(long long));
 ^
scripts/Makefile.build:197: recipe for target 'libbb/messages.o' failed
make[2]: *** [libbb/messages.o] Error 1
Makefile:741: recipe for target 'libbb' failed
make[1]: *** [libbb] Error 2
make[1]: Leaving directory '/tmp/bedrocklinux-userland/src/busybox'
Makefile:280: recipe for target 'build/bin/busybox' failed
make: *** [build/bin/busybox] Error 2

**Comment by DevPump** [comment]
Temporary fixed by making the Makefile static
Included patch file.

===
diff --git a/Makefile b/Makefile
index 5c02a2d..7b29eba 100644
--- a/Makefile
+++ b/Makefile
@@ -25,12 +25,13 @@ clean_source_busybox:
 src/busybox/.success_retreiving_source:
 	mkdir -p src/busybox
 	# get latest stable version
-	git clone --depth=1 \
-		-b `git ls-remote --heads 'git://git.busybox.net/busybox' | \
-		awk -F/ '$$NF ~ /stable$$/ {print $$NF}' | \
-		sort -t _ -k1,1n -k2,2n -k3,3n -k4,4n -k5,5n | \
-		tail -n1` 'git://git.busybox.net/busybox' \
-		src/busybox && \
+	git clone git://git.busybox.net/busybox -b 1_23_stable src/busybox
+#	git clone --depth=1 \
+#		-b `git ls-remote --heads 'git://git.busybox.net/busybox' | \
+#		awk -F/ '$$NF ~ /stable$$/ {print $$NF}' | \
+#		sort -t _ -k1,1n -k2,2n -k3,3n -k4,4n -k5,5n | \
+#		tail -n1` 'git://git.busybox.net/busybox' \
+#		src/busybox && \
 		touch src/busybox/.success_retreiving_source
===

**Comment by paradigm** [comment]
Fixed it by disabling the new 1.24 features in c401c025c4a783c30339016edce08b6c248e489b
