### ISSUE TITLE
X11 cursor setting synchronization

### ISSUE THREAD

**Issue by paradigm** [bedrocklinux/bedrocklinux-userland#56]
Users have reported different strata using different X11 cursors.  This setting should be standardized across strata.

**Comment by raphael-costa** [comment]
I ran into this issue today, I'm using Debian configured to use Breeze theme for both Qt and GTK applications but my Firefox from Arch Linux was unable to see that and was falling back to Adwaita, the solution was `pacman -S breeze breeze-gtk`.

Unless there is a configuration file somewhere specifying hard paths, I don't think it's possible to fix this issue without integrating into the package manager and automatically creating symlink farms for example.

**Comment by paradigm** [comment]
Do you know where X11 cursors are stored on disk, or how applications learn about them?  The feature is missing not because I couldn't figure out how to synchronize things, but rather that I haven't taken the time to figure out how that subsystem of Linux/X11/whatever works, which is a prerequisite step.

Bedrock Linux has a fairly capable set of tools for things like this that would remove the need to integrate with package managers.  I know how to synchronize fonts, for example (although I've not yet implemented it).  If none of the existing solutions end up working for cursors, I'm inclined to spend time thinking of other solutions rather than throwing in the towel.

**Comment by raphael-costa** [comment]
`pacman -Ql breeze|grep cursor` points me to `/usr/share/icons/{breeze_cursors,Breeze_Snow}/cursors`, oddly all of this seems to be in `/bedrock/brpath/icons`. I'll try uninstalling breeze from Arch and rebooting.

**Comment by paradigm** [comment]
I haven't seen this again with Poki's new architecture.  If it does happen to reoccur with Poki, people are free to re-open it.
