### ISSUE TITLE
Cannot install proprietary Nvidia drivers, probably bru's fault

### ISSUE THREAD

**Issue by paradigm** [bedrocklinux/bedrocklinux-userland#6]
The Nvidia proprietary Linux driver installer dies with SIGBUS on Bedrock Linux
1.0alpha4 Flopsie due, likely, to a bug in Bedrock Linux's `bru` utility.
Relevant strace output is below.  Hopefully this is sufficient information to
hunt down the issue.

Various notes:
- Note the installer seems to copy files via mmap()ing them.
- There seems to be some kind of alignment issue that bru isn't happy about in one instance of mmap().
- Note that if the `./nvidia.icd` file is replaced with an empty file, the
  nvidia driver installs correctly; this issue is not triggered in that
  situation.  No way to have an alignment issue if there is nothing to align.

The following lines starting with a `#` are my own comments added to help explain what is going on.

    # Logging that it is about to install /etc/OpenCL/vendors/nvidia.icd
    write(1, "\33[34;16H\33[37m\33[44metc/OpenCL/vendors/nvidia.icd\n\33(B\33[0;7m\33[32m\33[40m \33[35;88H\33(B\33[0m\33[32m\33[40m5%\33(B\33[m\33[39;49m\33[37m\33[40m", 119) = 119
    rt_sigaction(SIGTSTP, {0x7fc16c203bf0, [], SA_RESTORER|SA_RESTART, 0x7fc16c64e420}, NULL, 8) = 0
    # stat()'ing directory structure in case the installer will have to create a directory (which it does not)
    stat("/etc", {st_dev=makedev(0, 22), st_ino=1, st_mode=S_IFDIR|0755, st_nlink=52, st_uid=0, st_gid=0, st_blksize=4096, st_blocks=8, st_size=4096, st_atime=2014/05/14-18:19:24, st_mtime=2014/05/14-18:20:02, st_ctime=2014/05/14-18:20:02}) = 0
    stat("/etc/OpenCL", {st_dev=makedev(0, 22), st_ino=14, st_mode=S_IFDIR|0700, st_nlink=3, st_uid=0, st_gid=0, st_blksize=4096, st_blocks=8, st_size=4096, st_atime=2014/05/14-18:20:02, st_mtime=2014/05/14-18:20:02, st_ctime=2014/05/14-18:20:02}) = 0
    stat("/etc/OpenCL/vendors", {st_dev=makedev(0, 22), st_ino=21, st_mode=S_IFDIR|0700, st_nlink=2, st_uid=0, st_gid=0, st_blksize=4096, st_blocks=8, st_size=4096, st_atime=2014/05/14-18:20:02, st_mtime=2014/05/14-18:21:13, st_ctime=2014/05/14-18:21:13}) = 0
    # Here it opens the file to copy with fid=5
    open("nvidia.icd", O_RDONLY) = 5
    # Here it opens the file location to put the new file.  Note O_CREAT is used in case the file does not exist.  Note that this is in "/etc" on which is mounted bru.
    open("/etc/OpenCL/vendors/nvidia.icd", O_RDWR|O_CREAT|O_TRUNC, 0444) = 6
    # Here it gets the size of the nvidia.icd file to copy.  It does this in order to set the trailing NULL for the null-terminated string for the output file.
    fstat(5, {st_dev=makedev(8, 17), st_ino=6275211, st_mode=S_IFREG|0644, st_nlink=1, st_uid=0, st_gid=0, st_blksize=4096, st_blocks=8, st_size=22, st_atime=2014/05/14-18:20:25, st_mtime=2013/08/27-04:11:08, st_ctime=2014/05/14-18:20:28}) = 0
    # Here it seeks to the relevant location based on the fstat() above to place the NULL
    lseek(6, 21, SEEK_SET)   = 21
    # Write the NULL in place
    write(6, "\0", 1)        = 1
    # Here it mmap()'s the input file
    mmap(NULL, 22, PROT_READ, MAP_SHARED, 5, 0) = 0x7fc16cde2000
    # Here it mmap()'s the output file, in the /etc directory in bru.  Which results in the SIGBUS below.
    mmap(NULL, 22, PROT_READ|PROT_WRITE, MAP_SHARED, 6, 0) = 0x7fc16cde1000
    --- SIGBUS (Bus error) @ 0 (0) ---
    rt_sigaction(SIGTSTP, {SIG_IGN, [], SA_RESTORER|SA_RESTART, 0x7fc16c64e420}, {0x7fc16c203bf0, [], SA_RESTORER|SA_RESTART, 0x7fc16c64e420}, 8) = 0
    write(1, "\33[39;49m\33[37m\33[40m\33[H\33[2J", 25) = 25
    rt_sigaction(SIGTSTP, {0x7fc16c203bf0, [], SA_RESTORER|SA_RESTART, 0x7fc16c64e420}, NULL, 8) = 0
    write(1, "\33[39;49m\33[98d\33[K\33[98;1H\33[?12l\33[?25h", 35) = 35
    write(1, "\33[?1049l\r\33[?1l\33>", 16) = 16
    ioctl(1, SNDCTL_TMR_TIMEBASE or TCGETS, {c_iflags=0x4000, c_oflags=0x1, c_cflags=0xbf, c_lflags=0x8a31, c_line=0, c_cc[VMIN]=1, c_cc[VTIME]=0, c_cc="\x03\x1c\x7f\x15\x04\x00\x01\x00\x11\x13\x1a\x00\x12\x0f\x17\x16\x00\x00\x00"}) = 0
    ioctl(1, SNDCTL_TMR_STOP or TCSETSW, {c_iflags=0x4100, c_oflags=0x5, c_cflags=0xbf, c_lflags=0x8a3b, c_line=0, c_cc="\x03\x1c\x7f\x15\x04\x00\x01\x00\x11\x13\x1a\x00\x12\x0f\x17\x16\x00\x00\x00"}) = 0
    ioctl(1, SNDCTL_TMR_TIMEBASE or TCGETS, {c_iflags=0x4100, c_oflags=0x5, c_cflags=0xbf, c_lflags=0x8a3b, c_line=0, c_cc="\x03\x1c\x7f\x15\x04\x00\x01\x00\x11\x13\x1a\x00\x12\x0f\x17\x16\x00\x00\x00"}) = 0
    unlink("/tmp/nv-JbD2dG") = 0
    write(2, "Received signal ", 16) = 16
    write(2, "SIGBUS", 6)    = 6
    write(2, "; aborting.\n", 12) = 12
    exit_group(135)          = ?

Here's the same section of the strace output with bru unmounted (where it completes successfully)

    25005 18:48:34 write(1, "\33[3G\33[37m\33[44mBacking up: /etc/OpenCL/vendors/nvidia.icd\n\33[3G\33(B\33[0;7m\33[32m\33[40m  \33[13;80H\33(B\33[0m\33[32m\33[40m1%\33(B\33[m\33[39;49m\33[37m\33[40m", 133) = 133
    25005 18:48:34 rt_sigaction(SIGTSTP, {0x7fc39c56dbf0, [], SA_RESTORER|SA_RESTART, 0x7fc39c9b8420}, NULL, 8) = 0
    25005 18:48:34 open("/var/lib/nvidia/log", O_WRONLY|O_CREAT|O_APPEND, 0666) = 5
    25005 18:48:34 fstat(5, {st_dev=makedev(8, 17), st_ino=3515544, st_mode=S_IFREG|0600, st_nlink=1, st_uid=0, st_gid=0, st_blksize=4096, st_blocks=8, st_size=71, st_atime=2014/05/14-18:48:34, st_mtime=2014/05/14-18:48:34, st_ctime=2014/05/14-18:48:34}) = 0
    25005 18:48:34 mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fc39d14c000
    25005 18:48:34 fstat(5, {st_dev=makedev(8, 17), st_ino=3515544, st_mode=S_IFREG|0600, st_nlink=1, st_uid=0, st_gid=0, st_blksize=4096, st_blocks=8, st_size=71, st_atime=2014/05/14-18:48:34, st_mtime=2014/05/14-18:48:34, st_ctime=2014/05/14-18:48:34}) = 0
    25005 18:48:34 lseek(5, 71, SEEK_SET)   = 71
    25005 18:48:34 lstat("/etc/OpenCL/vendors/nvidia.icd", {st_dev=makedev(8, 17), st_ino=3515567, st_mode=S_IFREG|0400, st_nlink=1, st_uid=0, st_gid=0, st_blksize=4096, st_blocks=8, st_size=22, st_atime=2014/05/14-18:48:26, st_mtime=2014/05/14-18:20:02, st_ctime=2014/05/14-18:48:26}) = 0
    25005 18:48:34 open("/etc/OpenCL/vendors/nvidia.icd", O_RDONLY) = 6
    25005 18:48:34 fstat(6, {st_dev=makedev(8, 17), st_ino=3515567, st_mode=S_IFREG|0400, st_nlink=1, st_uid=0, st_gid=0, st_blksize=4096, st_blocks=8, st_size=22, st_atime=2014/05/14-18:48:26, st_mtime=2014/05/14-18:20:02, st_ctime=2014/05/14-18:48:26}) = 0
    25005 18:48:34 mmap(NULL, 22, PROT_READ, MAP_SHARED, 6, 0) = 0x7fc39d14b000
    25005 18:48:34 munmap(0x7fc39d14b000, 22) = 0
    25005 18:48:34 close(6)                 = 0
    25005 18:48:34 stat("/etc/OpenCL/vendors/nvidia.icd", {st_dev=makedev(8, 17), st_ino=3515567, st_mode=S_IFREG|0400, st_nlink=1, st_uid=0, st_gid=0, st_blksize=4096, st_blocks=8, st_size=22, st_atime=2014/05/14-18:48:34, st_mtime=2014/05/14-18:20:02, st_ctime=2014/05/14-18:48:26}) = 0
    25005 18:48:34 open("/etc/OpenCL/vendors/nvidia.icd", O_RDONLY) = 6
    25005 18:48:34 open("/var/lib/nvidia/100", O_RDWR|O_CREAT|O_TRUNC, 0100400) = 7
    25005 18:48:34 fstat(6, {st_dev=makedev(8, 17), st_ino=3515567, st_mode=S_IFREG|0400, st_nlink=1, st_uid=0, st_gid=0, st_blksize=4096, st_blocks=8, st_size=22, st_atime=2014/05/14-18:48:34, st_mtime=2014/05/14-18:20:02, st_ctime=2014/05/14-18:48:26}) = 0
    25005 18:48:34 lseek(7, 21, SEEK_SET)   = 21
    25005 18:48:34 write(7, "\0", 1)        = 1
    25005 18:48:34 mmap(NULL, 22, PROT_READ, MAP_SHARED, 6, 0) = 0x7fc39d14b000
    25005 18:48:34 mmap(NULL, 22, PROT_READ|PROT_WRITE, MAP_SHARED, 7, 0) = 0x7fc39d147000
    25005 18:48:34 munmap(0x7fc39d14b000, 22) = 0
    25005 18:48:34 munmap(0x7fc39d147000, 22) = 0
    25005 18:48:34 fchmod(7, 0100400)       = 0
    25005 18:48:34 close(6)                 = 0
    25005 18:48:34 close(7)                 = 0
    25005 18:48:34 utime("/var/lib/nvidia/100", [2014/05/14-18:48:34, 2014/05/14-18:20:02]) = 0
    25005 18:48:34 unlink("/etc/OpenCL/vendors/nvidia.icd") = 0
    25005 18:48:34 write(5, "100: /etc/OpenCL/vendors/nvidia.icd\n4168248298 100400 0 0\n", 58) = 58
    25005 18:48:34 close(5)                 = 0
    25005 18:48:34 munmap(0x7fc39d14c000, 4096) = 0

There are work-arounds - the current documentation for installing proprietary Nvidia drivers has some hints - but they're all ugly.  It'd be much easier if end users can just run `sh NVIDIA-.... --no-kernel-module --no-x-check` to install the drivers in a new client.  Plus, whatever is causing this could pop up elsewhere.

To ease debugging, it may be useful to see if this can be repeated with a smaller/simpler program that repeats the relevant system calls rather than use the entire Nvidia driver installer.

**Comment by paradigm** [comment]
=============================================
Instructions to reproduce the bru/nvidia bug:
=============================================

Background: When /etc is mounted with `bru`, as is typical with a Bedrock Linux
system, the Nvidia proprietary Linux driver installer crashes during
installation.  After some investigation it was found to crash when installing
the "nvidia.icd" file.  After some `strace`'ing the exact system calls which
cause the problem were found.  Through these, the issue can be easily
reproduced.

1. Make and enter a directory to use for this venture

    $ mkdir ~/bru_nvidia_fix
    $ cd ~/bru_nvidia_fix

2. Get the Bedrock Linux source code (including/especially `bru`'s source)

    $ git clone "https://github.com/bedrocklinux/bedrocklinux-userland.git"
    $ cd bedrocklinux-userland

3. Get required third party source code

    $ ./bedrocklinux-installer source headers
    $ ./bedrocklinux-installer source musl
    $ ./bedrocklinux-installer source fuse

4. Compile `bru`.  Note you can reproduce this step later while debugging the
issue, after changing bru's source code.

    $ ./bedrocklinux-installer make bru

5. Copy `bru` to root of work directory

    $ cd ..
    $ cp bedrocklinux-userland/tmp/bedrocklinux-installer-tmp/src/bru/bru/bru .

6. Make a copy of the file the nvidia installer was trying to install:

    echo "libnvidia-opencl.so.1" > ~/bru_nvidia_fix/nvidia.icd

7. Verify the file is as desired:

    $ sha1sum nvidia.icd-orig
    c0f7cf95caee3fb99cdcada0ef1cac0dcc97040a  nvidia.icd-orig

8. Create temporary directories for `bru` to operate on.  There should be two
input directories (which `bru` will union) and one output directory (onto which
`bru` will be mounted).

    $ mkdir in1 in2 out

9. Create tool to reproduce issue, mimicing what the nvidia driver does.  This
tool essentially copies the "nvidia.icd" file from the pwd into to
"out/nvidia.icd" via `mmap()`.

    $ echo '
    #include <sys/types.h>
    #include <sys/stat.h>
    #include <fcntl.h>
    #include <stdio.h>
    #include <unistd.h>
    #include <sys/mman.h>
    #include <string.h>
    
    int main()
    {
        // open input file
        int src = open("nvidia.icd", O_RDONLY);
        // open/create output file
        //int dst = open("/etc/OpenCL/vendors/nvidia.icd", O_RDWR|O_CREAT|O_TRUNC, 0444);
        int dst = open("out/nvidia.icd", O_RDWR|O_CREAT|O_TRUNC, 0444);
        // get size of input file
        struct stat st_src;
        fstat(src, &st_src);
        // write a NULL byte at the very end of the output file
        lseek(dst, st_src.st_size-1, SEEK_SET);
        write(dst, "\0", 1);
        // mmap() both files to memory locations
        void* src_mmap = mmap(NULL, st_src.st_size, PROT_READ, MAP_SHARED, src, 0);
        void* dst_mmap = mmap(NULL, st_src.st_size, PROT_READ|PROT_WRITE, MAP_SHARED, dst, 0);
        // copy file via mmap()'d regions
        memcpy(dst_mmap, src_mmap, st_src.st_size);
        // clean up
        munmap(src_mmap, st_src.st_size);
        munmap(dst_mmap, st_src.st_size);
        close(src);
        close(dst);
        // return
        return 0;
    }
    ' > repro.c
    
    gcc -o repro repro.c

10. Mount bru.  Keep this window open to watch for if/when bru closes/crashes,
open up another terminal for the rest of the instructions.

    $ sudo ./bru ~/bru_nvidia_fix/out ~/bru_nvidia_fix/in1 ~/bru_nvidia_fix/in2 /foo

11. Run code to reproduce issue

    $ sudo -s
    # ./repro
    zsh: segmentation fault  ./repro

12. Clean up.

    # rm out/nvidia.icd
    # umount out # bru in other terminal should close
    # exit

13. Change bru's source at ~/bru_nvidia_fix/bedrocklinuxu-userland/src/bru to
fix issue so the repro program successfully copies the file and does not crash.

14. Repeat steps 4, 5, 10-14 as needed.

**Comment by paradigm** [comment]
=============================================
Instructions to reproduce the bru/nvidia bug:
=============================================

Background: When /etc is mounted with `bru`, as is typical with a Bedrock Linux
system, the Nvidia proprietary Linux driver installer crashes during
installation.  After some investigation it was found to crash when installing
the "nvidia.icd" file.  After some `strace`'ing the exact system calls which
cause the problem were found.  Through these, the issue can be easily
reproduced.

1. Make and enter a directory to use for this venture

    $ mkdir ~/bru_nvidia_fix
    $ cd ~/bru_nvidia_fix

2. Get the Bedrock Linux source code (including/especially `bru`'s source)

    $ git clone "https://github.com/bedrocklinux/bedrocklinux-userland.git"

3. Get required third party source code

    $ ./bedrocklinux-userland/bedrocklinux-installer source headers
    $ ./bedrocklinux-userland/bedrocklinux-installer source musl
    $ ./bedrocklinux-userland/bedrocklinux-installer source fuse

4. Compile `bru`.

    $ ./bedrocklinux-userland/bedrocklinux-installer make bru

5. Copy `bru` to root of work directory

    $ cp bedrocklinux-userland/tmp/bedrocklinux-installer-tmp/src/bru/bru/bru .

6. Make a copy of the file the nvidia installer was trying to install:

    $ echo "libnvidia-opencl.so.1" > ~/bru_nvidia_fix/nvidia.icd

7. Verify the file is as desired:

    $ sha1sum nvidia.icd
    c0f7cf95caee3fb99cdcada0ef1cac0dcc97040a  nvidia.icd-orig

8. Create temporary directories for `bru` to operate on.  There should be two
input directories (which `bru` will union) and one output directory (onto which
`bru` will be mounted).

    $ mkdir in1 in2 out

9. Create tool to reproduce issue, mimicing what the nvidia driver does.  This
tool essentially copies the "nvidia.icd" file from the pwd into to
"out/nvidia.icd" via `mmap()`.

    $ cat > repro.c <<EOF
    #include \<sys/types.h\>
    #include \<sys/stat.h\>
    #include \<fcntl.h\>
    #include \<stdio.h\>
    #include \<unistd.h\>
    #include \<sys/mman.h\>
    #include \<string.h\>
    
    int main()
    {
        // open input file
        int src = open("nvidia.icd", O_RDONLY);
        // open/create output file
        //int dst = open("/etc/OpenCL/vendors/nvidia.icd", O_RDWR|O_CREAT|O_TRUNC, 0444);
        int dst = open("out/nvidia.icd", O_RDWR|O_CREAT|O_TRUNC, 0444);
        // get size of input file
        struct stat st_src;
        fstat(src, &st_src);
        // write a NULL byte at the very end of the output file
        lseek(dst, st_src.st_size-1, SEEK_SET);
        write(dst, "\0", 1);
        // mmap() both files to memory locations
        void* src_mmap = mmap(NULL, st_src.st_size, PROT_READ, MAP_SHARED, src, 0);
        void* dst_mmap = mmap(NULL, st_src.st_size, PROT_READ|PROT_WRITE, MAP_SHARED, dst, 0);
        // copy file via mmap()'d regions
        memcpy(dst_mmap, src_mmap, st_src.st_size);
        // clean up
        munmap(src_mmap, st_src.st_size);
        munmap(dst_mmap, st_src.st_size);
        close(src);
        close(dst);
        // return
        return 0;
    }
    EOF
    
    gcc -o repro repro.c

10. Test to demonstrate repro works without bru mounted

    $ sudo -s
    \# ./repro
    \# sha1sum out/nvidia.icd
    c0f7cf95caee3fb99cdcada0ef1cac0dcc97040a  out/nvidia.icd
    \# rm out/nvidia.icd
    \# exit

11. Mount bru.  Keep this window open to watch for if/when bru closes/crashes,
open up another terminal for the rest of the instructions.

    $ sudo ./bru ~/bru_nvidia_fix/out ~/bru_nvidia_fix/in1 ~/bru_nvidia_fix/in2 /foo

12. Run code to reproduce issue

    $ sudo -s
    \# ./repro
    zsh: bus error  ./repro
    \# exit
    \# rm out/nvidia.icd
    \# umount out # bru in other terminal should close
    \# exit

13. Change bru's source at ~/bru_nvidia_fix/bedrocklinuxu-userland/src/bru to
fix issue so the repro program successfully copies the file and does not crash.

14. Repeat steps 4, 5, 10-14 as needed.

**Comment by xaaron** [comment]
root@buildserver:/home/builduser# strace ./repro 
execve("./repro", ["./repro"], [/* 24 vars */]) = 0
brk(0)                                  = 0xa07000
access("/etc/ld.so.nohwcap", F_OK)      = -1 ENOENT (No such file or directory)
mmap(NULL, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f1ff3dfa000
access("/etc/ld.so.preload", R_OK)      = -1 ENOENT (No such file or directory)
open("/etc/ld.so.cache", O_RDONLY|O_CLOEXEC) = 3
fstat(3, {st_mode=S_IFREG|0644, st_size=147689, ...}) = 0
mmap(NULL, 147689, PROT_READ, MAP_PRIVATE, 3, 0) = 0x7f1ff3dd5000
close(3)                                = 0
access("/etc/ld.so.nohwcap", F_OK)      = -1 ENOENT (No such file or directory)
open("/lib/x86_64-linux-gnu/libc.so.6", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\3\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\320\37\2\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0755, st_size=1844160, ...}) = 0
mmap(NULL, 3949184, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f1ff3815000
mprotect(0x7f1ff39cf000, 2097152, PROT_NONE) = 0
mmap(0x7f1ff3bcf000, 24576, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x1ba000) = 0x7f1ff3bcf000
mmap(0x7f1ff3bd5000, 17024, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7f1ff3bd5000
close(3)                                = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f1ff3dd4000
mmap(NULL, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f1ff3dd2000
arch_prctl(ARCH_SET_FS, 0x7f1ff3dd2740) = 0
mprotect(0x7f1ff3bcf000, 16384, PROT_READ) = 0
mprotect(0x600000, 4096, PROT_READ)     = 0
mprotect(0x7f1ff3dfc000, 4096, PROT_READ) = 0
munmap(0x7f1ff3dd5000, 147689)          = 0
open("nvidia.icd", O_RDONLY)            = -1 ENOENT (No such file or directory)
open("out/nvidia.icd", O_RDWR|O_CREAT|O_TRUNC, 0444) = 3
fstat(-1, 0x7fff7ffd11c0)               = -1 EBADF (Bad file descriptor)
lseek(3, 4294967294, SEEK_SET)          = 4294967294
write(3, "\0", 1)                       = 1
mmap(NULL, 4294967295, PROT_READ, MAP_SHARED, -1, 0) = -1 EBADF (Bad file descriptor)
mmap(NULL, 4294967295, PROT_READ|PROT_WRITE, MAP_SHARED, 3, 0) = 0x7f1ef3815000
--- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=0x7} ---
+++ killed by SIGSEGV (core dumped) +++
Segmentation fault (core dumped)
root@buildserver:/home/builduser#

**Comment by paradigm** [comment]
The underly issue was that `flush()` was not implemented.  Adding `flush()`
fixed it.  This will likely be resolved in the Nyla release.

**Comment by paradigm** [comment]
After additional analysis, `flush()` appeared to be a red herring.  Instead, it was the use of `creat()` instead of `open()` to implement FUSE's `create()`.  With this change, the issue is resolved.
