### ISSUE TITLE
brl flag to run through /bedrock/libexec/busybox sh

### ISSUE THREAD

**Issue by paradigm** [bedrocklinux/bedrocklinux-userland#68]
In practice, much of `brl`'s usage involves passing a shell the command to run.  Since some strata do not have their own shells, this can often require calling out to the (global) Bedrock busybox, like so:

```
brl /bedrock/libexec/busybox sh -c '<command>'
```

Since the shell call to simple commands is typically effectively the same as running running those commands directly, it is tempting to simply make calling out to Bedrock's busybox's shell the default.  However, that busybox is configured to prioritize its own executables over the environments.  If that change were made and if someone were to run:

```
brl ls --help
```

They'd find everything is from busybox, not the stratum local `ls`.

To solve this, give `brl` a new flag to indicate the command should be run in the busybox shell.  Something like so:

```
brl -s '<command>'
```

Would effectively translate too:

```
brl /bedrock/libexec/busybox sh -c '<command>'
```

and allow for things like:

```
brl /bedrock/libexec/busybox sh -c 'foo && bar'
```

**Comment by seungmlee** [comment]
Could this be implemented through recursively calling brl?
For example, using "-s" as the flag:

```
if [ "$1" = "-c" ]
then
    conditional=$2
    shift
    shift
elif [ "$1" = "-s" ]
    then
        shift
        ./$0 /bedrock/libexec/busybox sh -c $@
        exit
else
    conditional="/bedrock/libexec/busybox true"
fi
```

**Comment by paradigm** [comment]
Minor issue in your example: I don't think `./$0` works as a general solution.  Consider what happens if `$0` is a full path, but cwd is not at the root - there'll be no file at `.//bedrock/bin/brl`.  `$0` or `/bedrock/bin/brl` may work better, I think.  Your example also unnecessarily mandates `-s` comes before `-c` if we're using both.  Your example expresses the idea you're putting forth just fine, though, which I think was the goal.

I'd want to play with it a bit to build confidence, but the general theory you're proposing sounds about right.  I'd have been inclined to have a check for `-s` control whether a variable is empty or contains `/bedrock/libexec/busybox sh`, then run `brc` with the variable `$@`.  I tend to prefer avoiding recursion if there's a comparably clean alternative.  Either strategy should work fine, though.

I've mostly been putting off implementing this to think through the repercussions of doing this.  As noted in the original post, `brl -s ls --help` may not work as expected.  Is there a way to solve the underlying issue without raising possible confusion?  There may be a better alternative here I'm missing.  In the months since I made this issue, nothing has come to mind.

While thinking about this, I've also realized there's a non-trivial chance users may be surprised that executables bleed across strata here.  While that's a key Bedrock Linux feature, it may not be desired with some use cases of `brl` and `brc`.  There may be value in providing flags to `brl` and `brc` to disable cross-strata executables (i.e., remove the `/bedrock/brpath` items from the `$PATH`).  Either that, or make a new command for this - one that could act as a wrapper like `brc` (which could then be used in-line with `brl` and `brc`), or one that toggles the functionality for the given shell session (i.e. edits `$PATH`).  The conclusion there may influence if/how we do `brl -s`.

If we do implement `-s`, we may want to drop `-c`.  If we're guaranteed a shell with `-s`, I think using `-s` and `&&` may be more natural for people already comfortable with shell scripting.  Something like

	brl -s "brw apt-get | grep '(direct)$' && sh -c 'apt-get update && apt-get dist-upgrade'"

reads cleaner than

	brl -c 'brw apt-get|grep "(direct)$"' sh -c 'apt-get update && apt-get dist-upgrade'

**Comment by seungmlee** [comment]
About your third point, I'm going to approach it from the perspective of dropping the `-c` flag and fully embracing the `-s` flag. From my limited understanding, conflicts that arise from using brl `-s` are due to Busybox and GNU coreutils providing multiple same-named commands. Therefore, to both remedy the ambiguity problem and to keep functionality simple, my suggestion is to using the [Busybox file command with the '-name' flag](https://www.busybox.net/downloads/BusyBox.html). The following code will have some \<pseudo code\>, but I will explain what I'm trying to do. I'm imagining that the change to `-s` will result in commands in the form of `brl -s "$CONDITIONAL && sh -c $COMMAND"`, where `$1="-s"` and `$2=<stuff_in_quotes>`.
```
if [ "$1" -eq "-s" ]
then
    shift
    conditional=<parsing via busybox grep and busybox sed>
else
    conditional="/bedrock/libexec/busybox true"
fi
<for each command in $1, 
    #Not sure if sed can do this
    sed s/<command>/'busybox file -name <command>'
```
The conversion to their full path forms should work for all commands, regardless of whether the command can be called from both userlands or not. This is probably a naive look at it and probably won't work due to all of the symlinks, mounts, etc., but this is the best I could come up with. 

In regards to disabling cross-strata executables, I think creating a new command would be best option since it is the most flexible option and relatively less writing intensive, but there are a few downsides. Flags are more accessible to regular users. Also, as a new Bedrock Linux user, I sometimes feel overwhelmed and intimidated due to the number of br commands, and others might feel the same way if another command was made.

I agree in dropping the `-c` flag. As someone relatively new to Bedrock Linux and Bash scripting, I was initially confused as to why there were two `-c` flags when looking at the provided examples; I later realized that the second flag was for `sh`. Although this is obvious to anyone beyond a novice, I feel that getting rid of the flag gets rid of unnecessary possible confusion. Using `-s` and subsequently `&&` also shows a clearer distinction between the conditional and the command.

I apologize if I'm way off-base about any of these ideas.

**Comment by paradigm** [comment]
I tried re-reading what you've posted here a number of times and I don't quite follow it.  Maybe we're on different pages about what the goal of `brl -s` is, and what the problem with my original proposal to fix it is?  I didn't explain it well - both of my posts here assumed a fair bit of Bedrock Linux background.  I'll try to rephrase:

Bedrock Linux's ability to utilize features from different distros by putting those features into strata means that a given stratum doesn't need to be individually featureful.  A stratum could just be a single man page, for example - without even an associated man executable to read it.  All of the required support - such as a man executable - could come from other strata, which Bedrock Linux seamlessly combines.  Alternatively, strata *could* be featureful and contain the entire GNU utils suite; they don't have to be single-purpose or minimalistic.  *Most* usage of Bedrock Linux has it combine the various strata features like this.  Occasionally, however, you do want to single out a stratum and do something with/to/about it.  You can use [explicit access](http://bedrocklinux.org/1.0beta2/concepts.html#explicit) to specify which; in practice, this works fine.

Less often, you'll want to single out multiple strata and do something with them independently.  That's where `brl` comes in - it lets you run a command in the context of all of the enabled strata relatively easily.  For example, if you want to see what versions of `apt-get` you have installed, instead of having to run `apt-get --version` through a bunch of `brc commands - which is tedious - you can do it in one line with `brl apt-get --version`.  At first blush this was natively simple to use and implement.  However, after using it for a bit and thinking about it, I've found that the rules for what executable is used in a given situation can become confusing.  An executable could come from the given stratum `brl` is focused on, or a `brl` provided busybox (in case the stratum doesn't have a desired executable locally), or another stratum.  It isn't clear to me that there is a single way we can formalize the rules here to be intuitive; *whatever* we do is going to confuse someone.

My current proposal to resolve this revolves around providing two binary options:
- Enable/disable cross-stratum executables in a `brl` command.  For example, if the command includes `apt-get` but only some of the strata provide it, you can use this to set whether you want *all* the strata to use it either directly or implicitly per the usual Bedrock Linux mechanisms, *or* you could have it run *only* with the strata that provide it and get a no-such-file error for the rest.
	- We could make this a flag for `brl`, or we may try to make this a stand-alone command that can be combine with `brl`.  This may also be useful for `brc`.
- Enable/disable using busybox utilities for a given `brl` command.  This could be very useful if you want to do something with/to/about minimal strata.
	- If enabled, do we want the busybox command to take precedence over a locally available command?  For example, if busybox provides `ls` and the stratum has `ls` locally, which is desired?  Having busybox take precedence is easier to implement at the moment given how Bedrock Linux is currently designed, but the other way around is likely possible.

-----

Regarding the first half, I don't see what the actual problem is you're trying to solve.  My best guess is you're trying to find a way to guarantee a given version of a command is run, but I don't see how you're determining that that is the desired version.  How do you know the user wants *that* version versus another one?

Part of my confusion may be because I can't find the Busybox file command you're utilizing - I don't see it on the page you've linked, in busybox's menuconfig or .config or source after a brief skim.  My guess based on the context is that it expands an executable name into a file path, e.g. `file -name vim` outputting `/usr/bin/vim`?  If so, it doesn't clarify *which* version of the command the user desired.

It also looks like you're hoping a simple sed command can parse a possibly very complicated shell command.  It can't - determining if a given word is a command we can fiddle with versus something else is rather difficult.  For example, what if the command provided to brl included the very sed command you provided, with vim as the command: `sed s/vim/'busybox file -name vim'`.  That first "vim" there isn't a command, it's a regex pattern; we wouldn't want to replace that.

I also think we're on different pages about the proposal to drop `-c` and go with `-s` and `&&` instead.  If so, we wouldn't have a `conditional` variable anymore; it'd be the busybox shell effectively implementing that itself.  No need to do any parsing there on our part.  Try playing around with the `&&` feature of shells; see what `true && echo "right side runs"` and `false && echo "right side runs"` do.  The reason we didn't go with that originally is that without `-s` there's no guarantee the given stratum even has a shell, so `-c` was used to effectively implement the `&&` shell feature.  If we're guaranteed a shell, we can let the shell do that.

No worries about being off-base.  If nothing else, it shows me where people new to Bedrock Linux become off-base, and helps ensure I minimize the possibility in the future.  It's far to easy for me to only view things from my own point of view, with my unique level of experience about Bedrock Linux, and fail to properly manage things for use by others new to the project.

**Comment by seungmlee** [comment]
I fundamentally misunderstood the issue. I thought that there was a technical implementation issue that you hadn’t figured out yet rather than you trying to figure out the best default configuration and flags. The code was my tragically bad attempt at implementing the `-s` flag without truly understanding what brl and the goal were.

From my perspective, it makes the most sense to default to disabling cross-stratum executables and Busybox, which errs on the side of caution by lacking unintended side-effects. Despite the verbosity (which can be remedied with aliases), requiring the user to explicitly write out `brl /bedrock/libexec/busybox sh -c` would allow for: flexibility to alternatively use toybox, granular control of busybox vs local precedence, and a reminder that the core function is to execute local commands in a local environment. One common use case would be package management operations. Although Busybox also provides a `dpkg` command, a Debian user might run `brl dpkg <command>` assuming the native command. Because there are possible discrepancies between the busybox version and native version, I believe it is safer to print an error instead of potentially harming the system by defaulting to the Busybox version. For example, the user can write `brl dpkg -r <program> && brl /bedrock/libexec/busybox sh -c ‘dpkg -r <program>'` to first use the native versions of dpkg to remove a program and then the Busybox version (or the other way around if they wish). This way, brl has one function which can be supplemented with ‘&&’ and a flag/command to enable cross-stratum executables.

I sincerely apologize for mistyping and wasting your time as I meant to write `find` instead of `file`. Also, I now understand the format of the command: brl executes Busybox sh -> evaluate condition/true as true -> evaluate the command. As you explained, I now realize that the shell would evaluate the conditional without any manual parsing, which renders the grep,sed, and if statement parts of my code unnecessary.

**Comment by paradigm** [comment]
> I fundamentally misunderstood the issue. I thought that there was a technical implementation issue that you hadn’t figured out yet rather than you trying to figure out the best default configuration and flags. The code was my tragically bad attempt at implementing the -s flag without truly understanding what brl and the goal were.

I wasn't sufficiently clear.  When I write these issues the target audience is experienced Bedrock Linux users.  I (perhaps naively) expect the entry point into the project to be elsewhere, such as the IRC room.  I may need to revisit this practice.

> From my perspective, it makes the most sense to default to disabling cross-stratum executables and Busybox, which errs on the side of caution by lacking unintended side-effects.

I'm concerned there'll be unintended side-effects both ways, just for difference audiences.  Everything else in Bedrock Linux has this cross-stratum functionality (it's essentially the project's main selling point), and this being an exception could easily be a surprise for people who don't read/absorb the documentation adequately.  I can easily see people expecting it to do the cross-stratum stuff here.  However, I can also see people expecting it the other way around, given brl's goal.

My current gut feeling is the path of least surprise here is to continue to do the cross-stratum stuff just like every other bit of Bedrock Linux - essentially, aim for consistency - but provide a means to (temporarily) disable it that can be applied to or work with brl.

> Despite the verbosity (which can be remedied with aliases), requiring the user to explicitly write out brl /bedrock/libexec/busybox sh -c would allow for: flexibility to alternatively use toybox, granular control of busybox vs local precedence, and a reminder that the core function is to execute local commands in a local environment.

I don't think I'm following here.  I'm concerned we may still be on different pages. It seems you're proposing not providing the discussed `-s` flag, but rather maintaining the current status where typing (or aliasing/wrappinge/etc away)"/bedrock/libexec/busybox sh -c" is required for certain operations.  However, I don't see how any of your arguments for typing out /bedrock/libexec/busybox is preferable to providing `-s` as a short cut for effectively the same thing.  If `-s` is a problem, they can not use it just as well as they can not use "/bedrock/libexec/busybox sh -c".  They can put toybox in some global location and pass that as an argument instead, can chose to or not to use `-s` to control busybox versus local, and `-s` should serve as a reminder as well.

Taken another way, all these things seem to be arguing *for* the need for `-s` to encourage the benefits you've listed.  However, if that's what you intended, I'm not sure why you took the verbose route to it.

If you want to compare `-s` versus `/bedrock/libexec/busybox sh -c "..."`, the way I see it:

- In `-s`'s favor: The existence of `-s` advertises the use-a-global-busybox workflow that users may otherwise not consider or fail to absorb from parts of the documentation they didn't see as relevant.
- In `-s`'s favor: `-s` is shorter, which again encourages its use for users who wouldn't take the time to make aliases/functions/wrappers for it.
- Against `-s`: `-s` requires more code on our part.
	- However, it's a fairly trivial amount.  Effectively negligible.

> One common use case would be package management operations. Although Busybox also provides a dpkg command, a Debian user might run brl dpkg <command> assuming the native command. Because there are possible discrepancies between the busybox version and native version,

I absolutely agree this is a point of concern, and why I don't think `-s` should be default.  It's worth noting that Bedrock Linux controls the busybox at /bedrock/libexec/busybox - the one that `-s` would use - and so we can mandate whether or not it has `dpkg`.  I might be able to ensure it doesn't include `dpkg` or `rpm` to minimize the chance of this being an issue even with the user having to opt-in with `-s`.  However, we might end up needing `dpkg` and/or `rpm` for [brg](http://bedrocklinux.org/1.0beta3/plans.html#brg) - hard to say at this point if we're safe to make it explicitly verboten in that busybox.

>  I believe it is safer to print an error instead of potentially harming the system by defaulting to the Busybox version.

If busybox provides `dpkg` or `rpm`, catching this without false positives/negatives so we can block it or error being called from a `brl -s` or `brl /bedrock/libexec/busybox sh -c '...'` would be a fair bit of work.  We could do it naively and risk the false positives and negatives, but I'm concerned that'll annoy users with false positives or build trust and fail on the false negatives.  Given the difficulty of doing it right, I'm not sure we should pursue it.

> For example, the user can write brl dpkg -r <program> && brl /bedrock/libexec/busybox sh -c ‘dpkg -r <program>' to first use the native versions of dpkg to remove a program and then the Busybox version (or the other way around if they wish). This way, brl has one function which can be supplemented with && and a flag/command to enable cross-stratum executables.

Yup, that's roughly what I had in mind with the `-s` flag: provide a clean way to do both types of operations.

> I sincerely apologize for mistyping and wasting your time as I meant to write find instead of file.

No worries, happens to the best of us.

> Also, I now understand the format of the command: brl executes Busybox sh -> evaluate condition/true as true -> evaluate the command. As you explained, I now realize that the shell would evaluate the conditional without any manual parsing, which renders the grep,sed, and if statement parts of my code unnecessary.

Yup, that's what I had intended.  Glad we're on the same page here now.

**Comment by seungmlee** [comment]
Although I understood that you were considering the `-s` flag, I thought that bypassing it by directly typing out the command would be more modular and in the spirit of UNIX. I guess I was prioritizing brl doing one predictable job and having no flags to possibly confuse the user over being consistent with the rest of the br- commands and being user friendly.

**Comment by paradigm** [comment]
> Although I understood that you were considering the -s flag, I thought that bypassing it by directly typing out the command would be more modular and in the spirit of UNIX.

Hmm.  I'm not entirely sure I agree, but I'm having difficulty putting my counter argument into words.  I'll have to chew on this for a bit.  Even if I concede this point, I'm not sure that this philosophical argument, alone, is necessarily sufficient to give up the benefits `-s` would provide.

> I guess I was prioritizing brl doing one predictable job and having no flags to possibly confuse the user over being consistent with the rest of the br- commands and being user friendly.

I don't follow most of this sentence.  I think I'm missing or misinterpreting something.

- I can *somewhat* see how refraining from using `-s` is prioritizing doing one job.
	- I'd argue brl's job is to provide a convenience for a common workflow of doing something about/to/with every stratum.  This workflow often includes calls to `/bedrock/libexec/busybox sh`, in which case this is very much part of the job.  What would you consider brl's job?  Maybe I'm missing something.
- I don't see how removing `-s` makes brl more "predictable"
- I don't see how adding flags would necessarily confuse someone, provided they're well documented.  *Overwhelm*, if there's a ton of them, sure, or *maybe* confuse if there's many that seem to do the same thing, but those aren't the cases here - it'd just be two flags, `--help` and `-s` (as we can drop `-c` if we get `-s`).
- I don't see how the inclusion of `-s` makes brl more consistent with the rest of the `br-` commands.

-----

Instead of treating this as a binary choice of "adding `-s`" versus "keeping things as they are", it may be worth investigating possible alternative options.  I'll think about it for a bit.  Maybe there's a way to keep it feel UNIXy one-job without requiring tedious typing or confusion about what happens in certain contexts.

**Comment by paradigm** [comment]
Nyla's `brl` has been removed in favor of a completely different UI in Poki.
