### ISSUE TITLE
Export current stratum to use in PS1

### ISSUE THREAD

**Issue by du5tball** [bedrocklinux/bedrocklinux-userland#77]
When using brc to switch to a different stratum, I'd like to see in which stratum I currently am. An environment variable would be helpful in that, so it can be worked into the PS1 (at least on bash).

**Comment by nilesr** [comment]
It's also provided in the `/etc/bedrock_stratum` file

**Comment by nilesr** [comment]
I don't know if my email reply to this issue went through, but you can get the current stratum from `bri -n`

**Comment by du5tball** [comment]
Nope, I only see the comments that you made on here. Well that's easy then, issue closed :)

**Comment by paradigm** [comment]
My usual recommendation here is to call `bri -n` or `brw` (which is just a wrapper for `bri` - `brw` came first and became stuck in muscle memory before `bri` became a centralized tool to query for such information).

Thus, you could do something like:

	export PS1='$(brw):'

`/etc/bedrock_stratum` is essentially a cached version of `bri -n`/`brw`'s output.  You're welcome to use that, although I'm not completely sure it'll stay as it is going forward.  Is `/etc/` the right place for such a value?  I'm also not sure if the benefits of caching are worth it having that caching subsystem in place; it's not as though `brw` is terribly slow without it.

I considered having `brc` export an environment variable, but that would require handling the scenario where setting the environment variable failed (e.g. exhausted the relevant bit of memory).  I couldn't find any solutions to that with which I was happy.  `brc` is intended to get called implicitly all over the place, and if it fails debugging could be difficult.  If `brw` fails it should be obvious where to go to figure out what went wrong.

It may also be worth noting that while some people, coming from places like chroot or containers, find it natural to think about which stratum they are "in", it can be unnecessarily constraining.  Bedrock Linux is designed more around thinking about where things are *from*, or what they are associated with, where "you" are in Bedrock Linux.

For example, if you want to edit stretch's /etc/apt/sources.list, you *could* do:

	brc stretch
	vim /etc/apt/sources.list

in which case knowing which stratum providing your shell is important.  Or, alternatively, you could do:

	brc stretch vim /etc/apt/sources.list

in which case you're explicit about what you want and less dependent on context.  However, this then requires every stratum have its own editor, which can be wasteful in terms of disk space and confusing if there are differences between them.  The idea of Bedrock Linux is to get you get what you want from where you want; tying the editing of a configuration file to its associated distro's editor is an unnecessary constraint.

Instead, you could do:

	vim /bedrock/stratum/stretch/etc/apt/sources.list

This lets you use your preferred editor, and really need it installed once.  I, personally, do this, and so I haven't felt much need to place any stratum information into my prompt.  The downside here is the path is verbose.  I do some zsh magicks to save keystrokes:

	for stratum in $(bri -l)
	do
		hash -d "$stratum"="/bedrock/strata/$stratum"
	done

which then lets me do:

	vim ~stretch/apt/sources.list

which is tab-completable.

However, you're welcome to use whatever work flow works best for you.
