### ISSUE TITLE
awk command in installation script to extract stratum name from /etc/{os,lsb}-release includes quotes

### ISSUE THREAD

**Issue by Crestwave** [bedrocklinux/bedrocklinux-userland#85]
Commands are in lines 1173 and 1175. On, e.g., Void, the value is quoted, as in `ID="void"`. The quotes are included in the extracted output and thus hijacking fails if no arguments are passed due to them being disallowed characters. To fix this, you could simply source the file and use the variable instead, or do something to remove the quotes.

EDIT: Whoops; just noticed that this is already a known issue.

**Comment by paradigm** [comment]
Sourcing `os-release` seems the best option to me.  I'll see if I can distribute an update with that change in the near future.

**Comment by paradigm** [comment]
Should be fixed in 0.7.0beta2.
