### ISSUE TITLE
makepkg can't invoke pacman

### ISSUE THREAD

**Issue by SolitudeSF** [bedrocklinux/bedrocklinux-userland#90]
Fresh install of void and bedrock with fetched arch strata. Invoking makepkg returns this error message
```
sudo: /usr/sbin/pacman: command not found
==> ERROR: 'pacman' failed to install missing dependencies.
```
pacman obviously works, but isn't present at location reported by makepkg

**Comment by SolitudeSF** [comment]
after installing `base-devel` which includes `pacman`? issure is resolved.

**Comment by paradigm** [comment]
This is something I plan to document before Poki gets out of beta.  It's an area where Bedrock doesn't "just work", but requires a bit of a hint for what to do.

Bedrock's design assumes strata contain all their version/path-specific dependencies, and so if some process tries to run a command (or use a manpage, etc) that isn't available in the process' native stratum it's safe to get from other strata.  Package managers ensure this is true the vast majority of the time.  However, things like `makepkg` (and `./configure` scripts, etc) look for stuff in the environment without it necessarily being there, and thus can get confused on Bedrock systems.

On a native Arch system, if you run `makepkg` you'll get errors about missing dependencies and know what to install.  On Bedrock you can use `strat`'s `-r` flag to disable the cross-stratum binaries (and manpages, etc) to mimic this.  Next time `makepkg` acts funny, try `strat -r arch makepkg` - it should make it obvious what's missing.

It'd be great if this "just worked."  However, the only idea I have here - having `makepkg` implicitly do a `strat -r` - would generate *other* messages about missing dependencies when they're clearly on the system from other strata, and *also* confuse users.  I think the best we can do for now is ensure it is mentioned in some introductory material.  I'll see if I can make that happen in time for Poki's release.

**Comment by SolitudeSF** [comment]
just a faq page with common workarounds would be nice

**Comment by paradigm** [comment]
My current plan is to make a big table of various features and an indication of how well they work under Bedrock Linux.  Values could include "just works" for some things and a degree of workaround difficulty for others.  If some workaround is needed it will be documented accordingly.  I'll be sure to include `makepkg` in the table.
