### ISSUE TITLE
Fedora 29 as bedrock host

### ISSUE THREAD

**Issue by linusheinz** [bedrocklinux/bedrocklinux-userland#93]
I tried to hijack fedora 29 (encrypted install) but when I start the init system it freezes

**Comment by linusheinz** [comment]
Yes i think it is an issue related to that my first attempt with fedora was an automatic partitioned. The installer created a home and root   partition on lvm after the hijack the mounting of home failed . Then i removed the home partition and mounted everything on one partition on lvm  but it still failed

**Comment by paradigm** [comment]
I figured it out.  Nothing to do with lvm.  Rather, something about the hand off from the initrd-systemd to the userland-systemd goes awry.  I've got a local fix that I'm testing.  If all goes well, I'll include it in the next update.

**Comment by paradigm** [comment]
I've pushed an update.  I'm closing assuming the fix does in fact fix it.  If you hijack with `0.7.1` and the issue repeats feel free to re-open.
