### ISSUE TITLE
makepkg -si doesn't work. Arch bug with Bedrock Linux.

### ISSUE THREAD

**Issue by setsunati** [bedrocklinux/bedrocklinux-userland#95]
I installed Bedrock Linux on Linux Mint 19.1 Cinnamon and i want to install packages from AUR.

What i did:
brl fetch --list
sudo brl fetch arch 
sudo pacman -S krita

So far so good. Krita installed and works fine.

Now the problem, i couldn't figure out how to install packages from AUR since yay package is not installed by Bedrock Linux out of the box.

So i decided to install yay package this way:

git clone https://aur.archlinux.org/yay.git
cd yay
makepkg -si

This is where i encountered problem. makepkg -si doesn't work.

I get this error:
==> Making package: yay 9.0.1-3 (Friday 04 January 2019 04:07:14 PM IST)
==> Checking runtime dependencies...
==> Installing missing dependencies...
sudo: /usr/sbin/pacman: command not found
==> ERROR: 'pacman' failed to install missing dependencies.

**Comment by Mouvedia** [comment]
Sounds like #78

**Comment by SolitudeSF** [comment]
workaround, im pretty sure, is to use `strat -r <strat-name> makepkg -si`

**Comment by setsunati** [comment]
Did strat -r arch makepkg -si

I get this error:
==> WARNING: Cannot find the sudo binary. Will use su to acquire root privileges.
==> ERROR: Cannot find the strip binary required for object file stripping.

**Comment by SolitudeSF** [comment]
you need `base-devel` installed

**Comment by setsunati** [comment]
After doing 
pacman -S base-devel
cd yay
makepkg -si
makepkg -si now just works. Didn't need to use strata -r.

**Comment by setsunati** [comment]
I got Pamac GUI installed now. :)

Need to log out log in Linux Mint every time i install package from Arch repos, for software's installed from Arch repos to show up in Cinnamon Menu. Probably a minor bug with either Bedrock Linux or Cinnamon Menu.

Bedrock Linux needs to automatically install base-devel and yay package out of the box when you "sudo brl fetch arch" in order to fix this problem so future releases of Bedrock Linux wont have this problem i encountered. :)

**Comment by SolitudeSF** [comment]
you dont need these, if you dont use aur.
